### ISSUE TITLE
Ensure equinox.log.stream and equinox.coordinator still pass OSGi TCK

### ISSUE THREAD

**Issue by tjwatson** [eclipse-equinox/equinox#10]
Reminder to test the latest R8 OSGi TCK against the Equinox log.stream and coordinator implementations once eclipse-equinox/equinox.bundles#26 is in a build.

These two implementations provide the compatible implementations for the specification currently.  I don't foresee any issues.  But need to make sure all is good still.

**Comment by akurtakov** [comment]
@tjwatson Is there anything planned here?

**Comment by laeubi** [comment]
According to https://github.com/eclipse-equinox/equinox Equinox passes the [Coordinator Service Specification](https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.coordinator.html) and [Log Service Specification](https://docs.osgi.org/specification/osgi.core/8.0.0/service.log.html) so is this solved now @tjwatson ?

**Comment by tjwatson** [comment]
> According to https://github.com/eclipse-equinox/equinox Equinox passes the [Coordinator Service Specification](https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.coordinator.html) and [Log Service Specification](https://docs.osgi.org/specification/osgi.core/8.0.0/service.log.html) so is this solved now @tjwatson ?

I didn't do anything to fix it.

**Comment by laeubi** [comment]
> > According to https://github.com/eclipse-equinox/equinox Equinox passes the [Coordinator Service Specification](https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.coordinator.html) and [Log Service Specification](https://docs.osgi.org/specification/osgi.core/8.0.0/service.log.html) so is this solved now @tjwatson ?
> 
> I didn't do anything to fix it.

The issue says only that you wanted to make sure soemthing passes the TCK, I assume it is the case but wanted to make sure I do get it correctly.

**Comment by tjwatson** [comment]
> The issue says only that you wanted to make sure soemthing passes the TCK, I assume it is the case but wanted to make sure I do get it correctly.

Ah, sorry didn't look back at the history.  Though the tests were passing and then magically started passing.  I'll close this.
