### ISSUE TITLE
Long startup on certain simpleconfigurator plugin sets

### ISSUE THREAD

**Issue by andrey-kuznetsov** [eclipse-equinox/equinox#106]
Eclipse may freeze for a long time on restart after software installation and after other `bundles.info` changes.

Reproduction steps, tested on Ubuntu 20.04 and Windows 10:
- Install fresh Eclipse for RCP/RAP Dev 2022-06 or 2022-09-M2 (**not for Java Dev**).
- Launch it and install current stable [Bndtools](https://bndtools.org/installation.html) (v. 6.3.1 as of now).
- Confirm restart when the installation completes -- on restart, Eclipse hangs for about 2 minutes, CPU usage is 50..100%.

Next time Eclipse starts fast, but if someone changes `bundles.info` contents it freezes again (I just commented out/in the last line with snakeyaml bundle back and forth).

Debugging shows this happens during `simpleconfigurator` bundle startup. `main` thread is waiting on a latch without timeout in `ConfigApplier.refreshAllBundles()`, while `RefreshThread` is doing actual refresh for a long time, see [threads-2022-06-rcp-bndtools-restart.txt](https://github.com/eclipse-equinox/equinox/files/9427978/threads-2022-06-rcp-bndtools-restart.txt), [threads-2022-06-rcp-next-launch.txt](https://github.com/eclipse-equinox/equinox/files/9427979/threads-2022-06-rcp-next-launch.txt).

I came to this while investigating the similar issue happened flakily for an applied RCP application even without `bundles.info` change, after long period of inactivity. In that case, `main` waits in `refreshAllBundles()` again while `Refresh Thread` tries to acquire `simpleconfigurator`'s state change lock, currently owned by `main`, for `osgi.module.lock.timeout` seconds. After timeout occurs, startup continues normally. Likely, nobody noticed this until the default value for this timeout was changed from 5 to 30. See
[ecl-deadlock-osgi-3.16.100.v20201030-1916.txt](https://github.com/eclipse-equinox/equinox/files/9428067/ecl-deadlock-osgi-3.16.100.v20201030-1916.txt). The app is built with some older Eclipse (with o.e.osgi-3.16.100.v20201030), unfortunately I cannot rebuild it with the current stable version immediately.

**Comment by tjwatson** [comment]
Can you try M3?  Issue #93 recently got fixed and should be in M3.

**Comment by andrey-kuznetsov** [comment]
I tried M3 SDK, not reproducible. But it definitely depends on the plugin set. For previous builds, it only fired in RCP/RAP flavor (not available for M3 afaik).

**Comment by laeubi** [comment]
I still se very long startup times in m2e tests and custom RCP application when one uses the default setting, using batchSize=1 then "fixes" the problem.
