### ISSUE TITLE
Windows console launcher (eclipsec.exe) not reading vmargs from eclipse.ini when there is no console window

### ISSUE THREAD

**Issue by jonathan-meier** [eclipse-equinox/equinox#117]
When the console launcher `eclipsec.exe` on Windows is started without a console window, the `vmargs` specified in `eclipse.ini` are ignored. This can easily be tested e.g. by adding debugging arguments `-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8000` to the `eclipse.ini` of an Eclipse IDE installation.

Starting the Eclipse IDE running `eclipsec.exe` on the command line works as expected: The JVM waits for a debugger to attach with the message `Listening for transport dt_socket at address: 8000`.

Starting the Eclipse IDE using `Runtime.getRuntime().exec("eclipsec.exe")` (easiest to do with `jshell`) does not work as expected: The JVM does not wait for a debugger to attach and just runs the Eclipse IDE. Apparently, the `vmargs` specified in `eclipse.ini` are ignored. In fact, using `procmon` from SysInternals shows that in this case `eclipsec.exe` only attempts to read `eclipsec.ini` but not `eclipse.ini`.

Whether `eclipse.ini` is consulted in addition to `eclipsec.ini` to read the `vmargs` is determined by the function `isConsoleLauncher` which checks whether there is a console window or not:

https://github.com/eclipse-equinox/equinox/blob/a3a9628da771382ba2821b0b61228eb9c9946b6e/features/org.eclipse.equinox.executable.feature/library/eclipse.c#L1609-L1618

It turns out that there are ways to start the console launcher without a console window. One such case is via `Runtime.getRuntime().exec("eclipsec.exe")` which apparently uses the `CREATE_NO_WINDOW` flag when creating the process (see https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags).

The issue came up when running an Ant script that executes an eclipse application using its console launcher in an `exec` task. Ant uses `Runtime.getRuntime().exec("<command_line>")` internally. The workaround in this case is to explicitly specify the `eclipse.ini` file on the command line: `eclipsec.exe --launcher.ini eclipse.ini`.

**Comment by umairsair** [comment]
is this fix part of latest eclipse releases?

IIUC, the binaries are picked from following location and I don't see a new commit after this fix.. am I missing something here?

https://github.com/eclipse-equinox/equinox.binaries/tree/master/org.eclipse.equinox.executable/bin/win32/win32/x86_64
