### ISSUE TITLE
Equinox no longer resolves some bundles

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#119]
While analyzing a problem in Tycho with the new 3.18.100 version have compared previous versus current initial state of the framework and noticed that now some bundles are in the `INSTALLED` state, so I assumed they have some missing requirements, but when I request the bundle to start it just advances them to `RESOLVED`/`ACTIVE` state without a problem.

I have not found in the spec if it is _MANDATORY_ that the framework at least tries to resolve a bundle that is installed, but the life-cycle diagram here: http://docs.osgi.org/specification/osgi.core/8.0.0/framework.lifecycle.html#i3320885 seem to indicate that it somehow should advance to the `RESOLVED` state "if it resolves" (I just can't find if that should be automatic or could be triggered by some user action).

At least I see a problem with a bundle-listener that waits for resolved bundles to take further action now will never get notified because the bundle remains in the `INSTALLED` state.

@tjwatson can you help here? I think this is related to the recent optimization for speedup the resolving (even though I still see long startup times in Eclipse upgraded from 2022-06 > 2022-08) and I would guess a lot of code in the wild assumes a bundles is `RESOLVED` when all its requirements are fulfilled...

**Comment by laeubi** [comment]
This is a usual example:

https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.equinox.registry/src/org/eclipse/core/internal/registry/osgi/EclipseBundleListener.java

The listener listens to `BundleEvent.RESOLVED` if this event is never send it does not add items to the registry and thus all extension points from such a bundle are missing. As often extension points are not used in a dynamic way, it also does not help to start the bundle later on and lazy activated bundles will never be activated (by registry lookups)....

**Comment by laeubi** [comment]
Even worse, it seems that this is somewhat random when/if a bundle is resolved or installed state sometimes.

FYI @mickaelistria @akurtakov

**Comment by laeubi** [comment]
After some discussion with @tjwatson I'll close this as invalid because my initial assumption that all bundles are tried to be resolved once is not true but was a side-effect.

The only thing left might be that the https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.equinox.registry/src/org/eclipse/core/internal/registry/osgi/EclipseBundleListener.java should also take `INSTALLED` bundles into account.

**Comment by tjwatson** [comment]
> After some discussion with @tjwatson I'll close this as invalid because my initial assumption that all bundles are tried to be resolved once is not true but was a side-effect.
> 
> The only thing left might be that the https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.equinox.registry/src/org/eclipse/core/internal/registry/osgi/EclipseBundleListener.java should also take `INSTALLED` bundles into account.

This listener should not listen for `INSTALLED` events.  It should only act on bundles it knows are resolved.
