### ISSUE TITLE
Evaluate jpackage to provide launchers

### ISSUE THREAD

**Issue by vogella** [eclipse-equinox/equinox#12]
jpackage is a new standard introduced with Java 14 to provide native launchers for Java applicatitions.

Example blog post about it: https://alvinalexander.com/java/how-use-jpackage-command-java-14-jdk-sdk/

Maybe we could also use this to provide our launchers? We already decided in the PMC to remove the support native splash loading via https://github.com/eclipse-equinox/equinox/issues/19 but this might be another opportunity to reduce / remove the need for our own launcher.

**Comment by merks** [comment]
Note that it needs to run natively on each platform.

**Comment by vogella** [comment]
> Note that it needs to run natively on each platform.

I believe that is the same for building the native launchers. At least that is what I think I heard from @nnemkin in the past.

**Comment by nnemkin** [comment]
jpackage is nice, but it's primary purpose is bundling the Java runtime and building native installers. Eclipse already has its own runtime bundles and installer.

Equinox launcher has at least 6 features that need to be ported to Java or cut before it could be replaced:
1. INI parsing.
2. Splash screen.
3. Activation, i.e. opening files in the same workbench instance.
4. Restarting the workbench after updates etc.
5. Graphical dialog if errors happen before Java/SWT is loaded.
6. Update via p2. The launcher is split into a p2-updatable library and a stub executable.
