### ISSUE TITLE
Consume org.apache.jasper.glassfish and javax.servlet.jsp from maven central

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#126]
I'm currently testing having better maven infos in equinox and found that currently there is one "bad boy" that comes from the prereq.target:

```
<location includeAllPlatforms="true" includeMode="slicer" type="InstallableUnit">
	<unit id="javax.servlet.jsp" version="2.2.0.v201112011158"/>
	<unit id="javax.servlet.jsp.source" version="2.2.0.v201112011158"/>
	<unit id="org.apache.jasper.glassfish" version="2.2.2.v201501141630"/>
	<unit id="org.apache.jasper.glassfish.source" version="2.2.2.v201501141630"/>

	<!-- This is the last build of the CVS sourced Orbit repository - this was a subrepo of the recommended Orbit
	   for 2022-03. Due to Bug 568936 this is not included in 2022-06 recommended Orbit repos and beyond.
	   The intention is to migrate the above (where possible) to newer sources, such as pulling from
	   maven central. -->
	<repository location="https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository/"/>
</location>
```
This also seem to rely on older orbit releases...

@akurtakov @HannesWell can you tell why we need the orbit ones here? Can we contribute to the upstream project somehow to get OSGi meta-data there, or maybe wrap the items? Is this anywhere used outside of equinox and we probably make this more local?

**Comment by akurtakov** [comment]
IIRC upstream artifacts are using different names and the whole jsp story is kind of a mess e.g. jasper being produced by tomcat, repackaged by glassfish in the past (but not any more), bundling old version of ecj and so on and on. Someone would have to spend the time to discover what the current state of affairs is and what we can use in maintainable way nowadays.

**Comment by laeubi** [comment]
DO you know for what we actually need all this? I think you recently changed that JSP are precompiled... I sadly don't know enough in that area to help out much, but it seems this is a danger of becoming unmaintained already...

**Comment by akurtakov** [comment]
There are all the org.eclipse.equinox.[jsp|http]. bundles. Eclipse Help system is based on these but they are also used by other things IIRC but I don't know the details . @tjwatson and @rotty3000  are the knowledgable people on the topic.

**Comment by mickaelistria** [comment]
As mentioned by @akurtakov , that cannot be just a replacement in .target as upstream do use different Bundle-SymbolicNames. So consumers would also need to adapt. In such case, the best started is to
1. add new upstream bundles in eclipse-sdk-prereqs.target
2. update all consumers (bundles, features, products...) of older bundles to use newer ones (or use import-package)
3. Upon completion, remove older bundles for .target.

All that is not so trivial

**Comment by laeubi** [comment]
@mickaelistria I searched for `org.apache.jasper` and it seems only be used internally in equinox itself, thats why I wonder if this is really something used "across platform", also the equinox.jasper parts seem only be used by `org.eclipse.help.webapp` ... so this seems to be a very narrow use-case and everyone just hopes there will never break anything and one needs never touch anything. The equinox part also uses lots of deprecated API ...
