### ISSUE TITLE
Bug 286463 - [launcher] Add env variables to executation environment 

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#143]
Moved from https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463

Jody Garnett CLA Friend 2009-08-12 20:47:59 EDT

I seem to be depending on functionality that is available in the run application 
menu; but cannot be reproduced when an RCP application is packaged up for release.

The uDig application makes use of some java extensions (ie to the bootclasspath) in the form of Java Advanced Imaging, Image IO and https://imageio-ext.dev.java.net/. It is this last extension that is troubling in that it depends on a couple of environmental variables used by a library called GDAL. These environmental variables document where some data files are to be picked up from. Ideally I would like these to be picked up from an unpacked plugin shipped with my application in order to avoid any chance of version conflicts.

From the Run menu in eclipse I can specify the required environmental variables and everything works. When I package up the RCP application for release there is no facility (either as part of the product definition; or execution environment definition) to reproduce these settings.

Changing the environment of the running java process is not something that can be done from a Java application (there is no access to the C putenv(cEnvString1) function) and will need to be accomplished by the launcher?

I would personally consider documenting this as part of the execution environment (http://wiki.eclipse.org/Execution_Environment_Descriptions) which the launcher refers to.

For anyone else in a similar situation - the uDig development community have produced a series of temporary workarounds on a platform by platform basis however this is not ideal.
- a bat file for windows
- a shell script for unix
- modification of plist for mac osx

The obvious workaround (setting a global environmental variable in an installer) is a bit of an imposition on the host computer; and would open up my application to being exposed to version differences between libraries.

[tag] [reply] [−] Comment 1 Thomas Watson CLA Friend 2009-08-13 09:06:39 EDT

Can you give us an example of a .ee file with some env variable definitions that you are thinking of?

[tag] [reply] [−] Comment 2[ Jody Garnett](mailto:jody.garnett@gmail.com) CLA Friend 2009-08-13 20:27:40 EDT

Here are the contents of the udig.bat file:

  set GDAL_DATA=%cd%\gdal_data\
  set GDAL_DRIVER_PATH=%cd%\jre\bin\

  START /B udig_internal %*

If I was to express this same information in a ee file I would expect something similar to how classpaths are handled by "ee.bootclasspath" or others...
- ee.env=GDAL_DATA=C:\java\udig\gdal_data;GDAL_DRIVER_PATH=C:\java\udig\jre\bin

Or something open ended:
- ee.env.GDAL_DATA=C:\java\udig\gdal_data
- ee.env.GDAL_DRIVER_PATH=C:\java\udig\jre\bin

Both options communicate the same information; I like the second one better .. 

Note the ee file already allows: "java.home" which amounts to an environmental variable setting.

[[tag](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#)] [[reply](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#add_comment)] [[−]](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#) Comment 3 Jody Garnett CLA Friend 2009-08-13 20:32:31 EDT

Created attachment 144489 [details]
example bat file used to start an RCP app with specific environment

[[tag](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#)] [[reply](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#add_comment)] [[−]](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#) Comment 4[ Jody Garnett](mailto:jody.garnett@gmail.com) CLA Friend 2009-08-13 21:01:07 EDT

Created attachment 144490 [details]
example sh file used to start an RCP app with specific environment

[[tag](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#)] [[reply](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#add_comment)] [[−]](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#) Comment 5[ Jody Garnett](mailto:jody.garnett@gmail.com) CLA Friend 2009-08-13 21:07:18 EDT

Created attachment 144491 [[details]](https://bugs.eclipse.org/bugs/attachment.cgi?id=144489&action=edit)
Example Info.plst adding env variables to a mac osx application

[[tag](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#)] [[reply](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#add_comment)] [[−]](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#) Comment 6 Martin Oberhuber CLA Friend 2010-05-06 09:09:56 EDT

This is very similar to bug 215689 which requests support for setting environment variables in the launcher.ini.

In my understanding (which may be wrong), the launcher.ini file is for setup specific to a product or application but independent of any JVM. So it can also be used when your product doesn't ship a JVM of its own (such as the Eclipse SDK). The .ee files, on the other hand, are specific for the JVM execution environment and seem to be usable only when your product ships a JVM of its own.

That being said, setting environment variables seems to be more tied to the application than to the JVM, so I'd argue that these would fit into the launcher.ini.

Would it be acceptable for you to have environment variable support in the launcher.ini ? Then I would argue that this bug can be marked as a duplicate of bug 215689.

[tag] [reply] [−] Comment 7[ Jody Garnett](mailto:jody.garnett@gmail.com) CLA Friend 2010-05-06 09:40:19 EDT

You are correct it *is* a duplicate problem. I think both reports just assume a good place to solve it....

I do not mind how the launcher is used to set env variables - controlling it from the ini file is fine; and indeed makes sense to me.

[[tag](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#)] [[reply](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#add_comment)] [[−]](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#) [Comment 8](https://bugs.eclipse.org/bugs/show_bug.cgi?id=286463#c8)[ Christoph Laeubrich](mailto:laeubi@laeubi-soft.de) CLA Friend 2018-10-30 07:26:34 EDT

Is there any progress on this?
We are hit bei a GTK-Bug (non pressable Buttons) that would require to set 

export GDK_NATIVE_WINDOWS=1

to make it work again, and we would like to specifiy that in the launcher.ini as well.

**Comment by merks** [comment]
The title appears to be asking for doing this via the execution environment but that long thread seems to reach the conclusion that this should be possible via the `<product>.ini` which to me makes more sense...

I wonder who is going to work on updating all the native launchers for this...

**Comment by laeubi** [comment]
@merks I just copied it "as is" so it do not get lost (no idea if bugzilla will be available "forever"), so whatever seems suit best ...

**Comment by mbooth101** [comment]
>  should be possible via the <product>.ini which to me makes more sense...

Agreed. I know the plural of anecdote is not anecdata, but I also have a use-case for this....

I have a RCP application that uses JavaFX and causes segfault on Wayland systems because of JavaFX's hard dep on X11 so I've been carrying a patch to the launcher like this in my downstream rebuilds of Eclipse: https://src.fedoraproject.org/rpms/eclipse/blob/f34/f/prefer_x11_backend.patch

Being able to set this in the ini file would be much less intrusive.
