### ISSUE TITLE
Open File Handle on Bundle

### ISSUE THREAD

**Issue by juergen-albert** [eclipse-equinox/equinox#159]
With bnd we make have use of the on the fly Bundle reload after sources are build. Up to equinox 3.17.100.v20211104-1730 this works flawless. Starting with 3.17.200.v20220215-2237 until the latest release version (3.18.100 I believe), bndtools starts to complain under Windows that it can't the delete the bundle jar anymore as another process is still using it. 

It seems that the FileHandel is not released after install. As it works with Felix and with the mentioned older Versions, I believe it to be something like an unclosed InputStream in equinox as the bnd code here looks pretty solid in that regard.

**Comment by HannesWell** [comment]
Can you trace somehow where the such unclosed resource is opened? It will then likely be trivial to fix it.

**Comment by laeubi** [comment]
Not sure if OSGi is required to release any file handles (e.g. it might optimize to not read everything into memory and thus keep the jar open to keep reading stuff from it if requested for a while), but why not just using the `org.osgi.framework.BundleContext.installBundle(String, InputStream)` and `org.osgi.framework.Bundle.update(InputStream)` then you have full control of the closing of the stream (even though the API states the stream is always closed anyways).

**Comment by juergen-albert** [comment]
@HannesWell Not really. I can only say that bnd uses the various `BundleContext.installBundle` methods and Windows and Java is usually not really forthcoming with the culprit. 

The only thing we see is:
![image002](https://user-images.githubusercontent.com/8199490/201981265-45d2422a-9d09-4fd9-9e67-747781be8f9c.png)

and that the file is held by javaw.exe

**Comment by HannesWell** [comment]
> @HannesWell Not really. I can only say that bnd uses the various `BundleContext.installBundle` methods and Windows and Java is usually not really forthcoming with the culprit.

To bad, because I have a similar problem with Xtext and don't know a elegant way to find such resource leaks either.

The only answswer I found in the internet was to do a heap analysis (e.g. with VisualVm) and search for open Stream objects.

So unless somebody else knows a good way to trace them, we probably have to check what has changed since then.

**Comment by juergen-albert** [comment]
@tjwatson The Bnd launcher explicitly deactivates references when it is running under windows. Don't ask my why, maybe @pkriens can tell us why.

@bjhargrave I have tried the file leak detector activ in eclipse and in the running framework that seems to be the culprit. Both constantly say `0 descriptors are open` even while I can see the open file in the Windows ResourceMonitor.

I can see the issue here at least.
3.17.100
```
Image	PID	Type	Handle Name
javaw.exe	35064	File	C:\Users\ungei\AppData\Local\Temp\osgi.16676134002345007939.fw\org.eclipse.osgi\10\0\bundleFile
javaw.exe	35064	File	C:\Users\ungei\AppData\Local\Temp\osgi.16676134002345007939.fw\org.eclipse.osgi\9\0\bundleFile
javaw.exe	35064	File	C:\Users\ungei\AppData\Local\Temp\osgi.16676134002345007939.fw\org.eclipse.osgi\8\0\bundleFile
javaw.exe	35064	File	C:\Users\ungei\AppData\Local\Temp\osgi.16676134002345007939.fw\org.eclipse.osgi\7\0\bundleFile
javaw.exe	35064	File	C:\Users\ungei\AppData\Local\Temp\osgi.16676134002345007939.fw\org.eclipse.osgi\6\0\bundleFile
javaw.exe	35064	File	C:\Users\ungei\AppData\Local\Temp\osgi.16676134002345007939.fw\org.eclipse.osgi\5\0\bundleFile
javaw.exe	35064	File	C:\Users\ungei\AppData\Local\Temp\osgi.16676134002345007939.fw\org.eclipse.osgi\4\0\bundleFile
javaw.exe	35064	File	C:\Users\ungei\AppData\Local\Temp\osgi.16676134002345007939.fw\org.eclipse.osgi\3\0\bundleFile
javaw.exe	35064	File	C:\Users\ungei\AppData\Local\Temp\osgi.16676134002345007939.fw\org.eclipse.osgi\2\0\bundleFile
javaw.exe	35064	File	C:\Users\ungei\AppData\Local\Temp\osgi.16676134002345007939.fw\org.eclipse.osgi\1\0\bundleFile
```

3.18.100
```
Image	PID	Type	Handle Name
Image	PID	Type	Handle Name
javaw.exe	14252	File	C:\Users\ungei\AppData\Local\Temp\osgi.16041108949202808537.fw\org.eclipse.osgi\10\0\bundleFile
javaw.exe	14252	File	C:\Users\ungei\.m2\repository\org\osgi\org.osgi.service.component\1.5.0\org.osgi.service.component-1.5.0.jar
javaw.exe	14252	File	C:\Users\ungei\AppData\Local\Temp\osgi.16041108949202808537.fw\org.eclipse.osgi\9\0\bundleFile
javaw.exe	14252	File	C:\Users\ungei\.m2\repository\org\apache\felix\org.apache.felix.scr\2.2.4\org.apache.felix.scr-2.2.4.jar
javaw.exe	14252	File	C:\Users\ungei\AppData\Local\Temp\osgi.16041108949202808537.fw\org.eclipse.osgi\8\0\bundleFile
javaw.exe	14252	File	C:\Users\ungei\.m2\repository\org\eclipse\platform\org.eclipse.equinox.console\1.4.500\org.eclipse.equinox.console-1.4.500.jar
javaw.exe	14252	File	C:\Users\ungei\AppData\Local\Temp\osgi.16041108949202808537.fw\org.eclipse.osgi\7\0\bundleFile
javaw.exe	14252	File	C:\Users\ungei\.m2\repository\org\apache\felix\org.apache.felix.gogo.shell\1.1.4\org.apache.felix.gogo.shell-1.1.4.jar
javaw.exe	14252	File	C:\Users\ungei\AppData\Local\Temp\osgi.16041108949202808537.fw\org.eclipse.osgi\6\0\bundleFile
javaw.exe	14252	File	C:\Users\ungei\.m2\repository\org\apache\felix\org.apache.felix.gogo.runtime\1.1.6\org.apache.felix.gogo.runtime-1.1.6.jar
javaw.exe	14252	File	C:\Users\ungei\AppData\Local\Temp\osgi.16041108949202808537.fw\org.eclipse.osgi\5\0\bundleFile
javaw.exe	14252	File	C:\Users\ungei\.m2\repository\org\apache\felix\org.apache.felix.gogo.command\1.1.2\org.apache.felix.gogo.command-1.1.2.jar
javaw.exe	14252	File	C:\Users\ungei\AppData\Local\Temp\osgi.16041108949202808537.fw\org.eclipse.osgi\4\0\bundleFile
javaw.exe	14252	File	C:\Users\ungei\.m2\repository\org\eclipse\emf\org.eclipse.emf.common\2.23.0\org.eclipse.emf.common-2.23.0.jar
javaw.exe	14252	File	C:\Users\ungei\AppData\Local\Temp\osgi.16041108949202808537.fw\org.eclipse.osgi\3\0\bundleFile
javaw.exe	14252	File	N:\tools\eclipse\misc\example\test\test.bundle\generated\test.bundle.jar
javaw.exe	14252	File	C:\Users\ungei\AppData\Local\Temp\osgi.16041108949202808537.fw\org.eclipse.osgi\2\0\bundleFile
javaw.exe	14252	File	C:\Users\ungei\.m2\repository\org\osgi\org.osgi.util.promise\1.2.0\org.osgi.util.promise-1.2.0.jar
javaw.exe	14252	File	C:\Users\ungei\AppData\Local\Temp\osgi.16041108949202808537.fw\org.eclipse.osgi\1\0\bundleFile
javaw.exe	14252	File	C:\Users\ungei\.m2\repository\org\osgi\org.osgi.util.function\1.1.0\org.osgi.util.function-1.1.0.jar
```

**Comment by bjhargrave** [comment]
> can tell us why

Using reference URLs will cause locking issues on windows which is why it is not used.

**Comment by tjwatson** [comment]
Are you installing with an InputStream or with a `file:` URL string?  Better yet, just tell us the exact `installBundle` call you are making.

I think the issue may be the changes in 68fa0c03747cf77307616b0fc644757a81e39578

In particular the change to call `Files.copy(in, file.toPath(), StandardCopyOption.REPLACE_EXISTING);` which I don't think is closing the inputsteam.  Although I see other paths in the code that don't look to ensure the given input stream is closed.

**Comment by HannesWell** [comment]
> I think the issue may be the changes in [68fa0c0](https://github.com/eclipse-equinox/equinox/commit/68fa0c03747cf77307616b0fc644757a81e39578)
> 
> In particular the change to call `Files.copy(in, file.toPath(), StandardCopyOption.REPLACE_EXISTING);` which I don't think is closing the inputsteam. Although I see other paths in the code that don't look to ensure the given input stream is closed.

Yes closing the input-stream is indeed missing(could be done by just using it as resource in a try block). Before the stream was closed and now IT isn't. Copy() does not close as far as I now. 

Other methods maybe leave that responsibility to the caller but this method at least hasn't done that before.

**Comment by HannesWell** [comment]
I just checked the callers of StorageUtil.readFile() and besides others the BundleContext.update(InputStream) method is eventually calling it. And that methods doc states about the passed InputStream:
`The input stream must always be closed when this method completes, even if an exception is thrown.`

So the stream has to be closed. But in general I'm not sure if the last part is ensured (but that didn't change with my commit you mentioned).

And the other callers also seem to rely on `StorageUtil.readFile()` to close the passed `InputStream`. I really wonder why this was not noticed before.

**Comment by laeubi** [comment]
> The input stream must always be closed when this method completes, even if an exception is thrown.

I find the text ambiguous and it is not clear if the **caller** or the **implementation** is responsible for closing the stream, anyways I always close streams regardless of what the method claims if I passing them ;-)

**Comment by juergen-albert** [comment]
Thanks for your quick reaction. Is there a Snapshot Version we can use to test?

**Comment by tjwatson** [comment]
> Thanks for your quick reaction. Is there a Snapshot Version we can use to test?

Not yet, but you could build the PR yourself.  If we merge today then it will be in tonight's I-Build.

Can you please answer my question:

> Are you installing with an InputStream or with a `file:` URL string? Better yet, just tell us the exact `installBundle` call you are making.

**Comment by juergen-albert** [comment]
> Can you please answer my question:

No Problem. BND uses `BundleContext.installBundle(String location)` with a file url.

**Comment by tjwatson** [comment]
> No Problem. BND uses `BundleContext.installBundle(String location)` with a file url.

The merged PR should fix the issue, but it is a bit unclear what past change broke this if you are using a `file:` URL location string.  That took a different path than the call to `Files.copy(in, file.toPath(), StandardCopyOption.REPLACE_EXISTING);`.  Regardless, the PR @HannesWell made fixed the `file:` location string URL case also.

**Comment by HannesWell** [comment]
I wonder if the OSGi TCKs should check if the `InputStream` passed to the BundleContext.install() methods are closed properly?

In general we could also consider to add a dedicated GH workflow that runs the OSGi TCKs against Equinox once a day or week (depending on how long they run). If they are fast enough we could even consider to run them as part of the verification build.

**Comment by tjwatson** [comment]
> I wonder if the OSGi TCKs should check if the `InputStream` passed to the BundleContext.install() methods are closed properly?

I think that would be a valid testcase to add to the TCK.

But there also needs to be a testcase for when an opaque URL location string is passed with no input stream.  That one would be a bit more tricky because the specification leaves it up to the implementation on how to handle location strings and how it can convert that to content for the bundle.  The typical implementation will try to convert that to a URL.  But, as we can see in Equinox, it does something a bit different for `file:` URLs so it can handle directory `file:` URLs properly.  So I think we need an Equinox specific test for the case where no input stream is provided.
