### ISSUE TITLE
No clear instructions how to build & test launcher binaries

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/equinox#16]
To review https://github.com/eclipse-equinox/equinox.framework/pull/2, I'm trying to understand how to **build** and **use** the built library in SDK.

To build, I did
```
cd /data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/library/gtk
./build.sh clean
./build.sh
```
That seem to run C build successfully.

So I can just take installed SDK and replace `eclipse` in the root of the SDK with generated `/data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/library/gtk/eclipse` file. Starting it in the shell opens Eclipse workspace dialog, but is that correct procedure? Also the binary seem to be much smaller compared to original one.

So I've tried following:

```
cd /data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature
mvn clean verify -Pbuild-individual-bundles -Drt.equinox.binaries.loc=/data/git/equinox.binaries/ -Dnative=gtk.linux.x86_64
```

I see that during the build
```
Copying /data/git/equinox.binaries/org.eclipse.equinox.executable/bin/gtk/linux/x86_64/eclipse to /data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/bin/gtk/linux/x86_64/eclipse

...

Attempting to rename: /data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/bin/gtk/linux/x86_64/eclipse to /data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/bin/gtk/linux/x86_64/launcher

...

Building zip: /data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/target/org.eclipse.equinox.executable-3.8.1700-SNAPSHOT.jar
```
In that `/data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/target/` directory I see 
`/data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/target/tmp/bin/gtk/linux/x86_64/launcher` executable, which is **binary different** to `eclipse` executable I've created before, but nearly same size of the original executable from SDK.

```
diff /data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/library/gtk/eclipse /data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/target/tmp/bin/gtk/linux/x86_64/launcher

Binary files /data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/library/gtk/eclipse and /data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/target/tmp/bin/gtk/linux/x86_64/launcher differ
```

I also see that there is native library `/data/git/rt.equinox.framework/bundles/org.eclipse.equinox.launcher.gtk.linux.x86_64/target/eclipse_11700.so` created that is packaged into `/data/git/rt.equinox.framework/bundles/org.eclipse.equinox.launcher.gtk.linux.x86_64/target/org.eclipse.equinox.launcher.gtk.linux.x86_64-1.2.500-SNAPSHOT.jar`
but this library again has different size as the one in `/data/git/rt.equinox.framework/features/org.eclipse.equinox.executable.feature/library/gtk/eclipse_11700.so`

So why there are different executables, which one is the right one and what is the correct procedure to build native executable bits?

**Comment by laeubi** [comment]
> So why there are different executables, which one is the right one and what is the correct procedure to build native executable bits?

From my limited knowledge (mostly tycho related) I can only give some hints here:

1. `launcher` is the "real" binary
2. during build it is enhanced with icons  (for windows)
3. the product build then might name it `eclipse`
4. the binary is also signed (for windows)

don't know if this helps much :-)

**Comment by vogella** [comment]
Please reopen if you plan to work on this

**Comment by Torbjorn-Svensson** [comment]
I don't know if this would help, but perhaps you could do something like what we do in eclipse to avoid having these manual steps?

https://github.com/eclipse-cdt/cdt/blob/main/native/org.eclipse.cdt.native.serial/native_src/Makefile

**Comment by jonahgraham** [comment]
This issue was auto-closed, before I found it I already started a new discussion on it here https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1407
