### ISSUE TITLE
Make "org.eclipse.equinox.http.servlet" bundle compatible with Tomcat Migration Tool

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipse-equinox/equinox#163]
Apache Tomcat provides a [Tomcat Migration Tool for Jakarta EE Software](https://tomcat.apache.org/download-migration.cgi) for automatic migration from "javax.servlet" to "jakarta.servlet" namespace. To make "org.eclipse.equinox.http.servlet" bundle compatible with this tool, the upper version limit for "javax.servlet.*" packages must be removed from the [MANIFEST.MF](https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.equinox.http.servlet/META-INF/MANIFEST.MF#L17).

A 5+ version of "javax.servlet" is extremely unlikely, and therefore the upper version constraint is useless.

This change is very important for Eclipse RAP project in order to make RAP application running on Jakarta EE 9+ container.

**Comment by akurtakov** [comment]
It's too late for Dec release, final build is already out. What do you think about providing the needed PR so we can merge it early after branching?
