### ISSUE TITLE
ConnectBundleEntry getLocalURL throws UnsupportedOperationException

### ISSUE THREAD

**Issue by nedtwigg** [eclipse-equinox/equinox#179]
When running Eclipse using the Atomos connector, `platform://` URLs get resolved as `ConnectBundleFile` rather than `FileBundleEntry`. That's not a problem in itself, except for this difference

https://github.com/eclipse-equinox/equinox/blob/bfbcf87790b03a42fa0b78cff2c65561208ba6a6/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/storage/bundlefile/FileBundleEntry.java#L94-L97

https://github.com/eclipse-equinox/equinox/blob/bfbcf87790b03a42fa0b78cff2c65561208ba6a6/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/connect/ConnectBundleFile.java#L79-L83

I bumped into this problem while implementing

- https://github.com/equodev/equo-ide/pull/36

In case it's useful, a testcase which reproduces this is to clone https://github.com/equodev/equo-ide at `7b46b2a2bd5dcd6be32a9711915983f394aa55ce` and either

- run `./gradlew IdeMainTest`
- or `./gradlew eclipse`, import the Solstice project into Eclipse, and run the main in `IdeMainTest`

To work around the `UnsupportedOperationException` I added this little hack https://github.com/equodev/equo-ide/pull/36/commits/fd0bb6f1c2cc36368618f77684261e7c9973e50f

**Comment by merks** [comment]
I think you're asking a bit much for reproducing a problem.  I don't want to have to install gradle to be able to reproduce a problem in Equinox...

Can you be more specific about what exactly your URL looks like relative to this documentation:

https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fplatform-scheme-uri.html

Ideally if you want something changed, you'd create a failing test case and then fix it with your change.   It's pretty easy to contribute:

https://github.com/eclipse-equinox/.github/blob/main/CONTRIBUTING.md

Probably org.eclipse.osgi.internal.connect.ConnectBundleFile.ConnectBundleEntry.getLocalURL() should just call org.eclipse.osgi.internal.connect.ConnectBundleFile.ConnectBundleEntry.getFileURL() just like org.eclipse.osgi.storage.bundlefile.FileBundleEntry.getLocalURL() calls org.eclipse.osgi.storage.bundlefile.FileBundleEntry.getFileURL() right?

**Comment by tjwatson** [comment]
The reproduction steps are in https://github.com/equodev/equo-ide/pull/36

I've been interacting with Ned on this issue and asked him to open this issue.  I know how to reproduce it.

> Probably org.eclipse.osgi.internal.connect.ConnectBundleFile.ConnectBundleEntry.getLocalURL() should just call org.eclipse.osgi.internal.connect.ConnectBundleFile.ConnectBundleEntry.getFileURL() just like org.eclipse.osgi.storage.bundlefile.FileBundleEntry.getLocalURL() calls org.eclipse.osgi.storage.bundlefile.FileBundleEntry.getFileURL() right?

Not exactly.  `FileBundleEntry.getLocalURL` simply calls `getFileURL()` because all resources in FileBundleEntry are already files on disk (this is for directory bundles, not JAR'ed bundles).  For connect bundles the framework has no idea what the form of the resource is (JAR, directory etc.).  My initial thought is to have `ConnectBundleEntry.getLocalURL` turn around and use the connect content class loader to lookup the resource URL and return that if found.

**Comment by merks** [comment]
Sorry for getting in the way!
