### ISSUE TITLE
switch to jakarta.servlet

### ISSUE THREAD

**Issue by Nutstree** [eclipse-equinox/equinox#183]
On bugzilla was already a report about this started in 2021: https://bugs.eclipse.org/bugs/show_bug.cgi?id=572286

Are there any updates or plans about this migration? We would like to use jetty11 in our RCP product, but it is still bundled with jetty10 which is using javax.servlet.

**Comment by laeubi** [comment]
If you are really concerned about this, please step up here (and let other interested people know) so the spec is updated:
- https://github.com/osgi/osgi/issues/551

otherwise this most  probably never happen in regard to http-service from equinox what is currently the source of javax.servlet most of the time in equinox (and probably eclipse platform).

Beside that, if you have a custom RCP app why not just remove the offending parts from it?

**Comment by tjwatson** [comment]
> So pax-web uses its own extension and equinox is using its own extension (and then probably even other has to), implementing the same service but can't interact... that sounds not very good idea compared to just search & replace `javax.servlet` -> `jakarta.servlet` in the spec ...

I don't get the scenario where users of pax-web need to interact with users of equinox extension to http service nor how that motivates the move to Jakarta.

As I've said in other places.  I think we should look into providing a javax.servlet based http service implementation on top of a jakarta based serlvet whiteboard implementation.

**Comment by Nutstree** [comment]
> otherwise this most probably never happen in regard to http-service from equinox what is currently the source of javax.servlet most of the time in equinox (and probably eclipse platform).
> 
> Beside that, if you have a custom RCP app why not just remove the offending parts from it?

Our application also uses the build in help function which uses jetty 10 as a base. We have also another module which uses jetty, which we updated already to jetty 11. Our product is plugin based, which is not capable of having 2 bundles loaded of the same name. At the moment we temporarily disabled jetty10, and thereby also disabling the help function. We are overlooking our options at the moment.

To be fair, I am lacking in depth knowledge. I was referring to "org.eclipse.equinox.http.jetty" and not aware it is depending on "org.osgi.service.http". I am in no position to advice or vote for what is better. I only asked the question as from my point of view everyone who is migrating to java17 is also migrating from javax.servlet to jakarta.servlet.

**Comment by laeubi** [comment]
> Our product is plugin based, which is not capable of having 2 bundles loaded of the same name.

You can just put all your bundles into a feature and then have a second feature that provides the help.

**Comment by ideas-into-software** [comment]
Closely related: Upgrade Apache Felix to Jakarta Servlet API 6.x (https://issues.apache.org/jira/browse/FELIX-6612). 

There are quite a lot of prerequisites, along with questions which will further clarify next steps to take. Kindly please post your comments / clarifications via https://issues.apache.org/jira/browse/FELIX-6612 to move this forward.
