### ISSUE TITLE
equinox.ds gone?

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#185]
On this page https://www.eclipse.org/equinox/bundles/ it is written:

> Declarative Services ([org.eclipse.equinox.ds](http://git.eclipse.org/c/equinox/rt.equinox.bundles.git/tree/bundles/org.eclipse.equinox.ds))[ status:green](https://www.eclipse.org/equinox/bundles/#legend)

As far as I can see Equinox no longer has its own DS implementation but uses felix.

**Comment by akurtakov** [comment]
Equinox web page is surely out of date in many places. It is hosted at https://github.com/eclipse-equinox/equinox-website feel free to fix as equinox.ds is no longer a thing.

**Comment by laeubi** [comment]
Is the same true for Wire Admin Service ([org.eclipse.equinox.wireadmin](http://git.eclipse.org/c/equinox/rt.equinox.bundles.git/tree/bundles/org.eclipse.equinox.wireadmin))?

**Comment by tjwatson** [comment]
> Is the same true for
> 
> > Wire Admin Service ([org.eclipse.equinox.wireadmin](http://git.eclipse.org/c/equinox/rt.equinox.bundles.git/tree/bundles/org.eclipse.equinox.wireadmin))?

Yes, the original maintainers of wireadmin were no longer active in the project and we had no evidence that anyone other than the original maintainers ever used the implementation.  In the end it was decided to stop building the bundle and remove the source from the main branch.

**Comment by tjwatson** [comment]
The same was true for Equinox DS except we actually really needed a stable implementation of DS for Equinox/Eclipse and the Felix implementation provided that for the project.
