### ISSUE TITLE
Unbounded HTTPSession Cache causes crash

### ISSUE THREAD

**Issue by ldbalomar** [eclipse-equinox/equinox#188]
Eclipse 4.15 (Equinox) has an unbounded cache where it keeps HTTP Sessions... They stay around until you run out of memory. This change was introduced in 4.5, and the idle sessions issue was discovered in 4.8... where a Jetty-specific fix was introduced. That fix does nothing when the app container is something other than Jetty (i.e. WebSphere Liberty).

The design of this cache seems to assume that the application instantiates the application server object and in such a use-case, the application has the necessary information to invalidate entries in the cache. The code also seems very specific to this use-case and jetty. Other use-cases are not addressed. 

I do not entirely understand the issue that was being addressed, so it is hard to tell if there is a general need for this cache. If this is essential to the correct running of the equinox bridge, we need a reliable way to expel idle sessions from the cache. I suspect that this is not always necessary, in which case, we need the cache to be conditionally created. 

When a J2EE application (WAR) using the equinox bridge is deployed to an application server, the app-server manages the http sessions, not the application.

Additional Info
Change was introduced: https://bugs.eclipse.org/bugs/show_bug.cgi?id=459349
Similar Infocenter (on Jetty) issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=541607
What prompted the change: https://bugs.eclipse.org/bugs/show_bug.cgi?id=436698

**Comment by ldbalomar** [comment]
We have written a variant of the infocenter fix that simply expels idle entries from the cache every 20 seconds. I don't think this is the long-term solution to the problem.

**Comment by akurtakov** [comment]
I don't think much have changed in this area but still versions you report are quite old so please make sure that you have tried latest versions first.

**Comment by ldbalomar** [comment]
Unfortunately, we were on 4.4.2... and we started the adoption of 4.15 two years ago (very long story). We can't simply adopt a later version for the server. It is another several person-years worth of work. We were unable to find a fix in a future release.

**Comment by ldbalomar** [comment]
@akurtakov I don't think many eclipse consumers are using the equinox bridge - this issue is apparent as soon as you have a concurrent load on the application.
