### ISSUE TITLE
Retire native splash loading

### ISSUE THREAD

**Issue by vogella** [eclipse-equinox/equinox#19]
This is a follow-up from a discussion about the usefullness of the native splash handler we had in the PMC call. 

As the Java code which shows the splash is executed relatively fast, it was indicated that we could stop loading the bmp at startup time and leave the loading of a potential splash to the Java splash handler.

WDYT @tjwatson @nnemkin @akurtakov

**Comment by akurtakov** [comment]
@nnemkin Are you working on this one? As I've been looking into adding Gtk 4.x support, not dealing with image loading would simplify it.
