### ISSUE TITLE
org.eclipse.equinox.device seem to fail some TCK tests

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#191]
Currently the org.eclipse.equinox.device seem to fail some TCK test see test file that can be opened in Eclipse:
[TEST-org.osgi.test.cases.device-8.1.0.202212101352.xml.zip](https://github.com/eclipse-equinox/equinox/files/10464046/TEST-org.osgi.test.cases.device-8.1.0.202212101352.xml.zip)

**Comment by laeubi** [comment]
@tjwatson are you aware of any users of those service that might be interested to complete the implementation to make it comply to the TCK? Or should we probably deprecate / remove that implementation?

**Comment by tjwatson** [comment]
> @tjwatson are you aware of any users of those service that might be interested to complete the implementation to make it comply to the TCK? Or should we probably deprecate / remove that implementation?

I am not aware of anyone that uses this.  I vote to deprecate. There have been no real fixes to this bundle in many years.  Anyone using it can continue to use the existing version already released.
