### ISSUE TITLE
newly released 3.10.0 of org.eclipse.platform:org.eclipse.equinox.preferences has unresolvable dependency

### ISSUE THREAD

**Issue by tombrus** [eclipse-equinox/equinox#2]
[[I do not know if this is the right way to file an issue, the Eclipse Foundation website lead me here....]]

We get build errors because the latest version 3.10.0 of `org.eclipse.platform:org.eclipse.equinox.preferences` seems to have a bogus dependency.

The pom contains: `<dependency><groupId>org.osgi.service</groupId><artifactId>org.osgi.service.prefs</artifactId><version>[1.1.0,1.2.0)</version></dependency>` where the groupId `org.osgi.service` does not seem to exist.

Should the groupId be `org.osgi` instead??

**Comment by tombrus** [comment]
Thanks for the reply @akurtakov.

Our builds are failing.... 😢 

Any idea when a fix version would show up at https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.preferences ?

**Comment by akurtakov** [comment]
Do you have link to your CI build failure? Make sure that you run with clean ~/.m2 folder.

**Comment by tombrus** [comment]
Thanks for the follow up. The CI is private unfortunately.
Cleaning the .m2 folder did not do the trick because it would redownload all, including the bogus dependency.
I found another workaround, I shared it in #54
Our CI is purring like a kitten again!
