### ISSUE TITLE
Some core tests seem to fail

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#200]
See this check:
https://github.com/eclipse-equinox/equinox/pull/199/checks?check_run_id=10845850784

there are currently one error and four failing tests, I can just not decide if we miss something in the test setup or if these are real failures.

**Comment by tjwatson** [comment]
I think all these tests are failing because of some setup needed for some run properties that setup some extra capabilities for ee matching and native code matching:

https://github.com/osgi/osgi/blob/19378f170291be6d36f02beb0f444940fe688340/org.osgi.test.cases.framework/bnd.bnd#L314-L323

**Comment by laeubi** [comment]
@tjwatson I was able now to pass the properties and reduce it to two failures:

https://github.com/eclipse-equinox/equinox/runs/11226062625

But I don't really understand why the remaining test fail it seem to be related to some native env alias testing. Did you previously run the TCK against equinox successfully? Do we need some special os (maybe windows instead of linux?)
