### ISSUE TITLE
Java profiles

### ISSUE THREAD

**Issue by vogella** [eclipse-equinox/equinox#208]
Currently I'm looking for the Java packages which Equinox is re-exporting because of https://github.com/reactor/reactor-core/issues/3338

I see that we have https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.osgi/profile.list that it seems to stop at Java9. Are these profiles are still used? If not where can I see which Java packages Equinox is re-exporting?

**Comment by akurtakov** [comment]
These profiles are still used for old non-modular JVMs. For modular JVMs it's calculated dynamically based on the modules available.

**Comment by vogella** [comment]
@akurtakov how can I see the available packages exported?

**Comment by laeubi** [comment]
This is more an issue with PDE than with Equinox, you already verified that at runtime (=Equinox) all is fine and only in the IDE (=PDE) you see warnings.

**Comment by vogella** [comment]
Yes, but it would still be nice to see which Java packages are available by Equinox so that I could report this to PDE as an error in validation.

**Comment by laeubi** [comment]
This depends on the JVM (and settings) you run Equinox with, so there is no normative way to know without running the framework.

**Comment by vogella** [comment]
How would PDE or any API get these packages?

**Comment by laeubi** [comment]
PDE has the concept of a "target environment" where you choose the JRE:
![grafik](https://user-images.githubusercontent.com/1331477/215747742-bdf134d5-efad-4ae1-8af9-f31984b7b938.png)

Then these JVM can be queried/inspected for packages
![grafik](https://user-images.githubusercontent.com/1331477/215748096-be130475-4f6f-4f67-a183-0b9f200d3d8c.png)

**Comment by HannesWell** [comment]
> How would PDE or any API get these packages?

For example:
https://github.com/eclipse-pde/eclipse.pde/blob/47ef407df3082de87f9e8adc26c517204433ce11/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java#L407-L454

I also suggested to add a corresponding API to `IExecutionEnvironment` and plan to implement it hopefully soon:
https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/175

**Comment by HannesWell** [comment]
> PDE has the concept of a "target environment" where you choose the JRE:

That's right, but it is not used very consequently as we already noticed in https://github.com/eclipse-pde/eclipse.pde/issues/429.

**Comment by vogella** [comment]
Thanks @HannesWell [this ](https://github.com/eclipse-pde/eclipse.pde/blob/47ef407df3082de87f9e8adc26c517204433ce11/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java#L407-L454) was what I was looking for. Thanks also to @laeubi and @akurtakov for the help.
