### ISSUE TITLE
ServiceCaller should be either more robust or better documented

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-equinox/equinox#209]
`ServiceCaller` [states](https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.equinox.common/src/org/eclipse/core/runtime/ServiceCaller.java#L134)
```
	 * @throws NullPointerException if any of the parameters are null
```
However, if all the parameters are not `null` it can still throw NPE from constructor, since `FrameworkUtil.getBundle(caller)` could return `null` [here](https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.equinox.common/src/org/eclipse/core/runtime/ServiceCaller.java#L295).

I would consider it as a bug, since current behavior contradicts with declared API contract. But may be there is another point of view regarding where the change should be done to make both code an docs consistent.

**Comment by laeubi** [comment]
> I would consider it as a bug, since current behavior contradicts with declared API contract.

I would consider it a but using `ServiceCaller` at all ... especially if it is used anywhere where `FrameworkUtil.getBundle(caller)` can return null, so probably it should better throw IllegalArgument Exception then.

**Comment by tjwatson** [comment]
I agree, an `IllegalArgumentException` is more appropriate.  What calling class would be using `ServiceCaller` that has no `Bundle`?

**Comment by laeubi** [comment]
> I agree, an `IllegalArgumentException` is more appropriate. What calling class would be using `ServiceCaller` that has no `Bundle`?

Some code uses `ServiceCaller` in stupid ways e.g. in an Activator(!) as a static initialized field, if you use such bundles outside OSGi and unluckily the Activator class is initialized it fails the class-loading with NPE ... but that's just a guess as I noticed that when working on Tycho.

**Comment by ruspl-afed** [comment]
My use case is running the plain junit test for a type that triggers `ServiceCaller`-dependent code for one of its dependencies. 
Do we have a good way to understand does particular type requires OSGI-running or not?

I used to prefer classes from "org.eclipse.equinox.common" bundle, that are either OSGi-neutral or robust enough to not fail without it. `ServiceCaller` seems to be different.

**Comment by laeubi** [comment]
I think the best would be to try fix that code, but `ServiceCaller` could also probably just return as if no service can be found if called outside OSGi.

**Comment by ruspl-afed** [comment]
Of cause I'll fix the code, since I have no other options for now. 
But, the static methods of `ServiceCaller` could handle this case.
Or, there should be a change in javadoc that says it could throw `IllegalStateException` if bundle cannot be resolved for a given caller for whatever reason.

**Comment by tjwatson** [comment]
> I think the best would be to try fix that code, but `ServiceCaller` could also probably just return as if no service can be found if called outside OSGi.

Silently returning when bundle is `null` may hide bugs in the calling code.  I favor `IllegalArgumentException` and updating the javadoc indicating that if the caller class bundle cannot be determined then it throws `IllegalArgumentException`

**Comment by ruspl-afed** [comment]
I would prefer `IllegalStateException`, because argument itself is pretty good `Class` instance. Why should any class instance care who loaded it and does thing like "bundle" ever exist?

**Comment by laeubi** [comment]
> I would prefer `IllegalStateException`, because argument itself is pretty good `Class` instance. Why should any class instance care who loaded it and does thing like "bundle" ever exist?

Do you like to suggest a Patch via PR?

**Comment by tjwatson** [comment]
> I would prefer `IllegalStateException`, because argument itself is pretty good `Class` instance. Why should any class instance care who loaded it and does thing like "bundle" ever exist?

The calling code should care.  With no bundle there is no chance of getting a service from the service registry for the caller.  So the ServiceCaller instance is of no use.

**Comment by tjwatson** [comment]
With that said, I can be convinced it is an `IllegalStateException`.  Not much difference to trade one runtime exception for another.

**Comment by ruspl-afed** [comment]
> With no bundle there is no chance of getting a service from the service registry for the caller.

That literally means that one always need to check `FrameworkUtil#getBundle(caller) != null` before using `ServiceCaller`.
Because without such a check the caller code could be moved to another place, and will still compile well, but will became invalid.
So, my initial question was: would `ServiceCaller` be so kind to do that check for me. Since the argument "Silently returning when bundle is null may hide bugs in the calling code. " is good enough, `ServiceCaller` will not be kind, but better documented instead. Fine.

BTW, the most of classes in the package fragment are OSGi-neutral, so it looks like this class would have better place in `org.eclipse.runtime.core` bundle. But it is where it is.
