### ISSUE TITLE
Considder Multi-Release jar for MultiplexingFactory

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#211]
This commit in MultiplexingFactory: https://github.com/eclipse-equinox/equinox/commit/77fda35b312c6da5c6ce1530829804f7512bae7c let me think that such "if java X or Y then do this or that" is better resolved by using MR jars, @tjwatson what do you think? There might be some obstacles at the moment but a use-case in platform seems a good opportunity to start solving them to have a real use-case...

**Comment by tjwatson** [comment]
My opinion is that MR jars have their own level of complexity that is greater than the reflective complexity here.

This code is already doing some pretty advanced (and nasty) things that require the use of reflection. Moving to MR jars will not remove the need for reflection and it will only remove the need for the try-catch-NoSuchMethodException clause.
