### ISSUE TITLE
Possible performance improvement for high frequency logging using EquinoxLogWriter

### ISSUE THREAD

**Issue by alxflam-work** [eclipse-equinox/equinox#221]
Hi,

i've been taking a look at [EquinoxLogWriter](https://github.com/eclipse-equinox/equinox/blob/a9db8e97f40f2ae514722225133ab80fff367bb5/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/log/EquinoxLogWriter.java) recently and noticed the following behavior:

`log(FrameworkLogEntry logEntry)` always creates a new `BufferedWriter` with a new `FileOutputStream` for the given log file as the `finally` block in `log` always sets the `writer` to null (`closeFile` is called). If one makes heavy usage of logging, this can be a performance issue: Say you log a large number of `FrameworkLogEntry`s, then the FOS is opened and closed for every single log invocation.

Wouldn't it be possible to improve performance by only re-creating the `BufferedWriter` when necessary: 

- once the log file changes by use of the setter: `setOutput` is already called by `setFile`, therefore the `writer` is closed and set to null
- once the log file rotates due to the max size restriction: `checkLogFileSize` already calls `setOutput` and therefore ensures the `writer` is closed and set to null if the log file changes  

As both `setFile` and `log` are synchronized, wouldn't it be possible to omit the `closeFile` call in the `log` method to keep the `writer` instance and thereby improving performance for consecutive log invocations? Sure, then there's an open FOS for the runtime of the equinox application, e.g. for the complete runtime of an eclipse RCP. But isn't that somewhat expectable for the log file? A new `dispose` method may be required which can be called to free the `writer` and any other members, this could be called e.g. by `EquinoxLogServices#stop`.

What do you think - is this something that could be improved as outlined? I may just not spot the reason why the `writer` is not reused.

Greetings,
Alex

**Comment by tjwatson** [comment]
The log writing code itself predates even Equinox.  IIRC the current may be necessary for things like the PDE log viewer so that it gets notified when the content of the file changes.  At the least we need to make sure the content is flushed to disk each entry write I think.

**Comment by alxflam-work** [comment]
@tjwatson i think `flush`ing the stream would be fine if the `writer` is cached, the performance is still improved as the `SecurityManager` checks as well as the native file opening are then still omitted. This still is a large improvement, e.g. 50k log invocations take ~2s if the writer is reused whereas closing and re-creating the writer on every log invocation yields ~40s. While such large numbers of log invocations usually do not occur, it will still be a minor performance improvement even if logging is not used that frequently.

Regarding the `LogView` i've checked the code and the view registers itself as a `LogListener` using the `LogReaderService`. Therefore, once the log view got created the `ExtendedLogReaderServiceFactory` will not only have the `EquinoxLogWriter` as a listener, but additionally the `LogView`. So the log view is informed about new logs without actually parsing them from the file. There are situations when the log file is actually parsed by the view, e.g. when the view is initially opened.

So i think that such a change should not affect the `LogView` in eclipse as long as `flush` is called for every log entry.

**Comment by laeubi** [comment]
If different classes access the same file, one only needs to make sure it can be shared (e.g. windows don't like to write a file that is currently opened by another process) so this should be checked both on windows/linux to work smoothly.

**Comment by tjwatson** [comment]
> If different classes access the same file, one only needs to make sure it can be shared (e.g. windows don't like to write a file that is currently opened by another process) so this should be checked both on windows/linux to work smoothly.

The log is either instance specific with a unique name contained in the framework storage area, or it has been set to the `.log` in the workspace data area which has to be locked first before we change the log location to the workspace data area.  So I don't think windows file locking behavior should be an issue here since multiple processes should not be using the same log file location.

**Comment by tjwatson** [comment]
@alxflam-work best way to get this done is to open a PR with your suggested changes.  Thanks.
