### ISSUE TITLE
Add 64bit RISC-V architecture support

### ISSUE THREAD

**Issue by Avimitin** [eclipse-equinox/equinox#240]
RISC-V is an open standard instruction set architecture based on established RISC principles. Adding support for riscv64 architecture will help other program relies on equinox be built on riscv64 machine.

**Comment by iloveeclipse** [comment]
@Avimitin : 
- do you plan to provide RISC-V support for full Eclipse, or to equinox only?
- do you plan to continue supporting RISC-V code in the future?
- do you plan to provide test machines that can run build & tests on RISC-V?
- probably more.

**Comment by Avimitin** [comment]
1. I am going to port equinox to riscv64 for now, but if there are other Eclipse project require riscv64 porting, I will try my best to help or contribute.
2. Yes, I will continue to support code that related to riscv64 architecture.
3. Yes, I can provide test machines (From qemu-system to real riscv64 hardware) for run and test code on RISC-V.
