### ISSUE TITLE
GitHub actions for PRs and Pushes not working

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-equinox/equinox#248]
PR #247 has failing actions, but they seem to be failing the same as they are on the master branch:

PRs failures look like this:

![image](https://user-images.githubusercontent.com/679236/231768477-cc4ad47a-cccb-49da-b15f-c5ac45abb20b.png)

master failures look the same:

![image](https://user-images.githubusercontent.com/679236/231768624-99ff86b1-f4cd-42b0-8565-ab2fb3fecb38.png)

**Comment by jonahgraham** [comment]
Best I can tell the build on GHA has been failing consistently since this was merged:

- #235

**Comment by laeubi** [comment]
The problem is that Github currently executes with `-T1C` option (in contrast to Jenkins) and the tests pull in some dependencies in a way that breaks parallel builds. I'll try to take a look at this next week.
