### ISSUE TITLE
Bug 577416 - Unify Console creation and interaction behaviour of Eclipse launcher

### ISSUE THREAD

**Issue by HannesWell** [eclipse-equinox/equinox#249]
_Originally reported as [Bug 577416](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577416)._
---
At the moment the behaviour of the Eclipse launcher regarding opening a OS-console and where print-out is written is different between the Windows and Linux/Mac Platform. Furthermore the influence on console creation of the "-consoleLog" argument (specified in the ini or on the CLI) is different.
Additionally on the Windows-Platform there are two executables for Eclipse the "eclipse.exe" and the "eclipseC.exe" (C written capital to emphasize it). The latter one was introduced with [Bug 173962](https://bugs.eclipse.org/bugs/show_bug.cgi?id=173962) to improve the launching from the console on Windows.

The following listing tries to summaries the different behaviour on Windows- and Linux/Mac Platform- when the eclipse executable is launched. Linux and Mac seem to have the same behaviour, if one runs "Eclipse.app/Contents/MacOS/eclipse" on the console.
In all cases the Splash-Screen pops up, after some time the workspace-selection-dialog and so on.

- Eclipse executable launched from file-explorer by double-clicking on it:
  - argument "-consoleLog" NOT specified:

    - Linux/Mac:
    no console opens, print-out is written nowhere

    - Windows eclipse.exe:
    no console opens, print-out is written nowhere

    - Windows eclipseC.exe:
    one Console opens, console contains print-out messages

  - argument "-consoleLog" specified:

    - Linux/Mac:
    no console opens, print-out is written nowhere

    - Windows eclipse.exe:
    one Console opens, console contains (more) print-out messages

    - Windows eclipseC.exe:
    one Console opens, console contains (more) print-out messages

- Eclipse executable launched from CLI:
  - argument "-consoleLog" NOT specified:

    - Linux/Mac:
    "./eclipse" command does not return before the eclipse-process terminates,
    launching console contains print-out messages

    - Windows eclipse.exe:
    eclipse.exe command returns immediately,
    launching console contains NO print-out messages,

    - Windows eclipseC.exe:
    eclipseC.exe command does not return before the eclipse-process terminates,
    launching console contains print-out messages

  - argument "-consoleLog" specified:

    - Linux/Mac:
    "./eclipse" command does not return before the eclipse-process terminates,
    launching console contains (more) print-out messages

    - Windows-eclipse.exe:
    eclipse.exe command returns immediately,
    launching console contains NO print-out messages.
    One additional console opens, which contains (more) print-out messages
    but is closed automatically when eclipse-process has terminates.

    - Windows-eclipseC.exe:
    eclipseC.exe command does not return before the eclipse-process terminates,
    launching console contains (more) print-out messages

In my opinion it would be ideal if the two executables for windows would become one (so that there is only one eclipse.exe) and the executables on all platforms would behave the following ways:

- Eclipse executable launched from file-explorer by double-clicking on it:
  - argument "-consoleLog" NOT specified:
    no console opens, print-out is written nowhere
  - argument "-consoleLog" specified:
    one Console opens, console contains (more) print-out messages

- Eclipse executable launched from CLI:
  - argument "-consoleLog" NOT specified:
    eclipse command does not return before the eclipse-process terminates,
    launching console contains print-out messages
  - argument "-consoleLog" specified:
    eclipse command does not return before the eclipse-process terminates,
    launching console contains (more) print-out messages

In that sense on Windows the eclipse.exe behaves already ideally when launched in the file explorer by double-clicking and `eclipseC.exe` behaves ideally on the CLI.
On Linux/Mac the launcher behaves almost ideal. The only suboptimal point is that no console opens when eclipse is launched from the file-explorer and `-consoleLog` is specified, which can be 'workd-around' by launching eclipse from the console. I think this is OK, because one looses print-outs when eclipse terminates due to immediate console closing. So it is likely that eclipse is launched from the console then.
So the main goal would be to make eclipsec.exe obsolete by making eclipse.exe use the launching console for print-outs and not returning immediately.

I don't know if this is possible (my C skills are only rudimentary and my native Windows API knowledge is de-facto zero) and I don't know if you would like to change the behaviour (in case it is possible), but I would like to discuss it.

I read in the initially mentioned bug, that you can either compile the launcher as console-application (and always get a console) or not. But that was disused for Windows XP and in the meantime Windows 10/11 might provide some improvements in that regard?

Maybe somebody else with more knowledge in the field can answer the technical question, otherwise I'm willing to make some research, given there is a will to improve it.
If it is possible and wanted, we would of course need a migration strategy.

**Comment by HannesWell** [comment]
For example the VisualVM launcher on Windows has the ability to detect if the parent process itself already has a console and can detaches itself to that.

https://github.com/oracle/visualvm/blob/f10ccb5a2d41291f170d9c25c98b56bd1e574b68/visualvm/launcher/windows-src/visualvmlauncher.cpp#L53

The magic probably happens here:
https://github.com/oracle/visualvm/blob/f10ccb5a2d41291f170d9c25c98b56bd1e574b68/visualvm/launcher/windows-src/o.n.bootstrap/utilsfuncs.cpp#L282-L348

And when a parent console is found it calls the `attachconsole` function.

https://learn.microsoft.com/en-us/windows/console/attachconsole

**Comment by Torbjorn-Svensson** [comment]
I think that the main reason why no one has tried this in the past is simply that no one had enough time and interest in the Windows platform to do the required modifications.
I also think that the number of files/functions involved might be in the way of having contributions from people that does not know the in-and-outs of how the launcher works in order fix some small issue.

**Comment by laeubi** [comment]
I don't think that `-consoleLog` is a good way to control this, e.g. you might want to redirect the in/out of a launched process but **not** start a console or attach to a running one!

Equinox has the `-console` that actually control if:

1. a terminal should be used / attach to the current console
2. a telnet port should be opened and connected as a TTY

**Comment by HannesWell** [comment]
This is still relevant.

**Comment by HannesWell** [comment]
I recently noticed that when running the VisualVM executable on Windows it seems not notice that it seems to be able to control from within the exe if a new console is used or the same console is reused:
https://github.com/oracle/visualvm/blob/9d104173cc67c6d6c9aa3a5ec56ae0786f9174db/visualvm/launcher/windows-src/visualvmlauncher.cpp#L53-L57

So I assume technically it seems possible to avoid the need for two executables for Windows (almost 20years later).
Of course we still have to discuss and decide what the default behavior is and what should be configurable and how.
