### ISSUE TITLE
testCircularityHandling (org.eclipse.equinox.ds.tests.tbc.DSTest) failed on GH

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#25]
See https://github.com/eclipse-equinox/equinox/runs/6918222246 I don't know if this is might a timing issue or due to parallel execution, on the Jenkins the test currently passes.

**Comment by jukzi** [comment]
happend 2 times again in https://github.com/eclipse-equinox/equinox/pull/104
