### ISSUE TITLE
Provide a mean to configure logger instances from system properties

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#26]
My intention from my previous comment was to leave an issue open.  I won't have time to look into a solution, but thought it would be useful to have an equinox specific config property that could configure defaults for logging contexts.  This default would be overwritten by config admin or LoggerAdmin if used.

_Originally posted by @tjwatson in https://github.com/eclipse-equinox/equinox/discussions/20#discussioncomment-2964144_

**Comment by rotty3000** [comment]
I'd like this, in fact a cool feature would be for the Equinox to provide gogo shell command to alter the log levels on the fly. Useful during testing/prototyping and should be a very simple class and inert when there is no shell present.
