### ISSUE TITLE
Produce correct module-info class for org.eclipse.osgi using BND

### ISSUE THREAD

**Issue by akurtakov** [eclipse-equinox/equinox#27]
Log is:
```
Comparator differences from current build
	/home/jenkins/agent/workspace/I-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20220616-0910
compared to reference repo at 
	https://download.eclipse.org/eclipse/updates/4.25-I-builds

1.  equinox/bundles/org.eclipse.osgi
   no-classifier: different
      module-info.class: present in baseline only
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]
```
at https://download.eclipse.org/eclipse/downloads/drops4/I20220616-0910/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

**Comment by akurtakov** [comment]
@tjwatson is module-info.class in o.e.osgi needed ? what could have caused it to no longer be generated/added

**Comment by sravanlakkimsetti** [comment]
module-info definition is provided in pom.xml https://github.com/eclipse-equinox/equinox/blob/48152cb7d8bbd2a2cedb253e57d53ccf6d5e9e77/bundles/org.eclipse.osgi/pom.xml#L51. This is not getting generated after equinox merge.

**Comment by sravanlakkimsetti** [comment]
There are extra maven tasks after merge. These extra maven tasks are causing the trouble.
Here ate the task lists
Old  : [log_old.txt](https://github.com/eclipse-equinox/equinox/files/8924894/log_old.txt)
New : [log_new.txt](https://github.com/eclipse-equinox/equinox/files/8924895/log_new.txt)

**Comment by sravanlakkimsetti** [comment]
specifically there are two tasks that are running extra now 
```
[INFO] --- tycho-source-plugin:3.0.0-SNAPSHOT:feature-source (feature-source) @ org.eclipse.osgi ---
[INFO] 
[INFO] --- tycho-p2-plugin:3.0.0-SNAPSHOT:p2-metadata (attach-p2-metadata) @ org.eclipse.osgi ---
[INFO] 
```
they are running just before add-module-info task.

**Comment by laeubi** [comment]
> they are running just before add-module-info task.

these should be independet from any other task generating sources, the more interesting would be if the moditec is running and if it issues any warning/errors.

**Comment by laeubi** [comment]
If I build it local I see a `module-info.class` included...

![grafik](https://user-images.githubusercontent.com/1331477/174240081-455d1a4a-5b12-466a-8436-dbe64aa74a1c.png)

**Comment by akurtakov** [comment]
If I understood correctly @sravanlakkimsetti he sees p2-metadata task ran before add-module-info task and 
comparator runs during p2-metadata task .

**Comment by sravanlakkimsetti** [comment]
> > they are running just before add-module-info task.
> 
> these should be independet from any other task generating sources, the more interesting would be if the moditec is running and if it issues any warning/errors.

you can see the log [here](https://download.eclipse.org/eclipse/downloads/drops4/I20220614-1800/buildlogs/mb220_buildSdkPatch.sh.log)

please look for section add-module-info. As far as I see there is no error/warnings

**Comment by laeubi** [comment]
> he sees p2-metadata task ran before add-module-info task and
> comparator runs during p2-metadata task .

Then this seems like a false positive here, the p2-metadata task is required to update the meta-data after generating the source bundle.

**Comment by laeubi** [comment]
So maybe one can disable the baseline compare for the extra metadata task?

**Comment by laeubi** [comment]
I think the problem is that moditec is currently bound to `<phase>package</phase>` while it actually should be `<phase>process-classes</phase>`

**Comment by akurtakov** [comment]
Sounds correct, if you're not doing the change I'll do it right now.

**Comment by laeubi** [comment]
Stupid moditec... or baseline-compare ;-)

I'll propose a patch using BND for the JPMS stuff...

**Comment by akurtakov** [comment]
Thanks, @laeubi !

**Comment by sravanlakkimsetti** [comment]
here are the decompiled class files 

Module-info from baseline : [module-info.txt](https://github.com/eclipse-equinox/equinox/files/8926893/module-info.txt)
Module-info from pr           : [module-info-frompr.txt](https://github.com/eclipse-equinox/equinox/files/8926884/module-info-frompr.txt)

The differences:
Missing 
```
provides org.osgi.framework.launch.FrameworkFactory with org.eclipse.osgi.launch.EquinoxFactory;
provides org.osgi.framework.connect.ConnectFrameworkFactory with org.eclipse.osgi.launch.EquinoxFactory;
uses org.osgi.framework.connect.FrameworkUtilHelper;
```

Added extra
```
org.osgi.service.condition
org.eclipse.osgi.storage
org.eclipse.osgi.storage.bundlefile
org.eclipse.osgi.storage.url
org.eclipse.osgi.storage.url.bundleentry
org.eclipse.osgi.storage.url.bundleresource
org.eclipse.osgi.storage.url.reference
org.eclipse.osgi.framework.util
org.eclipse.osgi.internal.cds
org.eclipse.osgi.internal.connect
org.eclipse.osgi.internal.container
org.eclipse.osgi.internal.debug
org.eclipse.osgi.internal.framework
org.eclipse.osgi.internal.framework.legacy
org.eclipse.osgi.internal.hookregistry
org.eclipse.osgi.internal.hooks
org.eclipse.osgi.internal.loader
org.eclipse.osgi.internal.loader.buddy
org.eclipse.osgi.internal.loader.classpath
org.eclipse.osgi.internal.loader.sources
org.eclipse.osgi.internal.location
org.eclipse.osgi.internal.log
org.eclipse.osgi.internal.messages
org.eclipse.osgi.internal.permadmin
org.eclipse.osgi.internal.provisional.service.security
org.eclipse.osgi.internal.provisional.verifier
org.eclipse.osgi.internal.service.security
org.eclipse.osgi.internal.serviceregistry
org.eclipse.osgi.internal.signedcontent
org.eclipse.osgi.internal.url
org.eclipse.osgi.internal.util
org.eclipse.osgi.internal.weaving
org.eclipse.osgi.framework.internal.reliablefile
org.apache.felix.resolver
org.apache.felix.resolver.reason
org.apache.felix.resolver.util
org.eclipse.core.runtime.adaptor
org.eclipse.core.runtime.internal.adaptor
```

Added 
```
requires java.management
```

**Comment by laeubi** [comment]
Missing:
> uses org.osgi.framework.connect.FrameworkUtilHelper;

I'm not an JPMS expert, but as the interface is embedded in the OSGi jar it seems strange to declare its uses? Please let me know why this should be included and I can report this to the BND project.

> provides org.osgi.framework.launch.FrameworkFactory with org.eclipse.osgi.launch.EquinoxFactory;
> provides org.osgi.framework.connect.ConnectFrameworkFactory with org.eclipse.osgi.launch.EquinoxFactory;

reported here: https://github.com/bndtools/bnd/issues/5288

> Added requires java.management

Could it be a transitive one?

> Added extra

can you explain which one are unexpected so we can report an issue to BND? Will it harm to have those added?

**Comment by tjwatson** [comment]
For anyone asking why the module-info is needed at all.  It is to allow the framework impl to be placed on the module path along with a launcher without it being treated as a JPMS automatic module.  In particular it is important for something called OSGi connect (from OSGi R8 core) that allows the framework and a set of bundles to have alternative sources of content from the typical JAR that is supported by default by all framework implementations.

The Apache Felix Atomos project (https://github.com/apache/felix-atomos) provides such a launcher and connect implementation and can be used with Equinox or Felix frameworks to load the launcher, framework and set of bundles contained a JPMS module layer as modules.  Once that can be done that that set of modules can then be jlink'ed into a jlink image that launches the framework and set of bundles with the minimal set of modules from the JVM.



> > uses org.osgi.framework.connect.FrameworkUtilHelper;
> 
> I'm not an JPMS expert, but as the interface is embedded in the OSGi jar it seems strange to declare its uses? Please let me know why this should be included and I can report this to the BND project.

Because the framework uses the Java ServiceLoader to discover `FrameworkUtilHelper` providers available on the classpath of the framework (or module Layer for JPMS).  In the case of JPMS, the module system will not allow ServiceLoader to discover providers from other modules unless the using module declares that it uses the service interface/class.



> > Added requires java.management
> 
> Could it be a transitive one?

I'm not aware of anything the framework needs out of `java.management`.  We may need help from BND to figure out what it thinks needs that.

> org.osgi.service.condition
This is an oversight in the current `pom.xml`.  An argument for automating the generation.

> org.eclipse.osgi.storage
> org.eclipse.osgi.storage.bundlefile
> org.eclipse.osgi.storage.url
> org.eclipse.osgi.storage.url.bundleentry
> org.eclipse.osgi.storage.url.bundleresource
> org.eclipse.osgi.storage.url.reference
> org.eclipse.osgi.framework.util
> org.eclipse.osgi.internal.cds
> org.eclipse.osgi.internal.connect
> org.eclipse.osgi.internal.container
> org.eclipse.osgi.internal.debug
> org.eclipse.osgi.internal.framework
> org.eclipse.osgi.internal.framework.legacy
> org.eclipse.osgi.internal.hookregistry
> org.eclipse.osgi.internal.hooks
> org.eclipse.osgi.internal.loader
> org.eclipse.osgi.internal.loader.buddy
> org.eclipse.osgi.internal.loader.classpath
> org.eclipse.osgi.internal.loader.sources
> org.eclipse.osgi.internal.location
> org.eclipse.osgi.internal.log
> org.eclipse.osgi.internal.messages
> org.eclipse.osgi.internal.permadmin
> org.eclipse.osgi.internal.provisional.service.security
> org.eclipse.osgi.internal.provisional.verifier
> org.eclipse.osgi.internal.service.security
> org.eclipse.osgi.internal.serviceregistry
> org.eclipse.osgi.internal.signedcontent
> org.eclipse.osgi.internal.url
> org.eclipse.osgi.internal.util
> org.eclipse.osgi.internal.weaving
> org.eclipse.osgi.framework.internal.reliablefile
> org.apache.felix.resolver
> org.apache.felix.resolver.reason
> org.apache.felix.resolver.util
> org.eclipse.core.runtime.adaptor
> org.eclipse.core.runtime.internal.adaptor

The rest look to be not exported at all or exported as `x-internal`.  I intentionally left private and `x-internal` packages out.  I wish I could just not export the `x-internal` packages at all.  But it seems weird that BND is specifying the packages that are not even exported (e.g. `org.apache.felix.resolver`

**Comment by laeubi** [comment]
The BND part is described [here](https://bnd.bndtools.org/chapters/330-jpms.html), also how to customize this, I have enabled "edit by maintainer", so one could simply switch to file tab of the PR and edit the file, because my knowledge to JPMS is to limited here.

Any obstacle should be reported to the BND people so this could be improved, I think it is much more useful to generate this stuff instead of us editing it manually.

**Comment by tjwatson** [comment]
I have little time to focus on this today with any urgency.  Can we not just accept the module-info is in a bad state for now and allow the I-Build to continue?  If you are waiting for me it may not be for more than a week.

**Comment by laeubi** [comment]
> Can we not just accept the module-info is in a bad state for now

I'm fine with that, so if you are... please approve the PR then and I'll merge it as soon as the build passes.

**Comment by tjwatson** [comment]
I've repurposed this issue to confirm the output of the module-info class is correct.  In particular we need to ensure the output can still be used for such things as Apache Felix Atomos.
