### ISSUE TITLE
Splash screen appears up side down on macOS 14

### ISSUE THREAD

**Issue by dnoan** [eclipse-equinox/equinox#272]
I am running Eclipse 2023-03 on the newly released macOS 14 beta. When launching Eclipse, at first the splash screen appears normal but after a few moments it turns up side down. This happens on both Intel and Apple silicon Macs with macOS 14.

**Comment by Phillipus** [comment]
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/772
