### ISSUE TITLE
Module j9stubs not found, required by org.eclipse.osgi

### ISSUE THREAD

**Issue by fipro78** [eclipse-equinox/equinox#274]
I tried to use the latest Equinox OSGi bundle 3.18.400 to check my OSGi deployment setup:

The Atomos use case is not running anymore. If I try to start the application via

```
java --add-modules=ALL-MODULE-PATH,java.net.http -p bundles -m org.apache.felix.atomos org.osgi.framework.system.packages=""
```

I get the following error:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module j9stubs not found, required by org.eclipse.osgi
```

If I understand correctly, the module-info.class is now generated via bnd. But it somehow now adds the requirement for j9stubs, which is not found anywhere. I can see it here https://github.com/eclipse-equinox/equinox/tree/master/bundles/org.eclipse.osgi/osgi but I don't think it is part of the resulting org.eclipse.equinox.osgi bundle and therefore org.eclipse.osgi does not work with Atomos on the module-path anymore.

**Comment by rotty3000** [comment]
Try adding `j8stubs` [here](https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.osgi/bnd.bnd#L2) with ignore=true

**Comment by tjwatson** [comment]
Should be fixed in the next I-Build.

**Comment by fipro78** [comment]
Just downloaded the latest I-Build and copied the org.eclipse.osgi bundle into my example. Works again as expected.
