### ISSUE TITLE
Adding help to plugin, getting PWC6349

### ISSUE THREAD

**Issue by bertush** [eclipse-equinox/equinox#291]
Adding Help to a plugin is not working. I get the error "PWC6349 Cannot find a java compiler for compilation"

I have followed the steps in the Vogella tutorial (https://www.vogella.com/tutorials/EclipseRCPHelpSystem/article.html)

Eclipse version 202306
JustJ 17

**Comment by akurtakov** [comment]
Can you provide a reproducer ? It's hard to guess what  goes wrong.
