### ISSUE TITLE
servletbridge FrameworkLauncher.searchFor not compatible with maven naming convension

### ISSUE THREAD

**Issue by rougeSE** [eclipse-equinox/equinox#297]
When building a WAR file to run the equinox OSGI container as part of a servlet, the org.eclipse.equinox.servletbridge.FrameworkLauncher tries and find the OSGI_FRAMEWORK bundle. It does this using the searchFor(), but this function assumes the filename of the bundle is <bundle name> followed by an "_" . This use of the "_" prevents osgi framework bundles that match the naming convention of <artifactname>-<version> from being found, which is the filename format when pulling the dependency using maven/gradle.

Suggest adding the "-" separator to the accept filter such as

 return candidate.getName().equals(target) || candidate.getName().startsWith(target + "_") || candidate.getName().startsWith(target + "-"); 

Looks like findMax() will also need enhancing as it is looking for "_" for extracting out the version number.

**Comment by rougeSE** [comment]
Thomas, thank you for finding the related bug fix, I will work on getting something submitted based on the pattern implemented here https://bugs.eclipse.org/bugs/attachment.cgi?id=62562&action=diff

**Comment by rougeSE** [comment]
PR up, https://github.com/eclipse-equinox/equinox/pull/298

**Comment by rougeSE** [comment]
@tjwatson , any chance this PR can get it? GitHub trying to mark this as stale.

**Comment by tjwatson** [comment]
> @tjwatson , any chance this PR can get it? GitHub trying to mark this as stale.

This should have been reviewed and merged by now.  Unfortunately we are too late in the cycle for the upcoming release 2024-03.  I will review and merge for 2024-06

**Comment by tjwatson** [comment]
@rougeSE I did review it and I had some comments in it that I was waiting for you to address.  Do you think you can have a look?
