### ISSUE TITLE
Pin this repository?

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/equinox#37]
As the others are not really important most of the time, it might be good to pin this one?

**Comment by akurtakov** [comment]
@tjwatson Only you can do it. Please pin this one and p2 repo.

**Comment by tjwatson** [comment]
I'm project lead, but I don't think I am an administrator of the eclipse-equinox organization.  At least I don't see an option to pin repositories in the repository tab of the organization as I would expect as an administrator.

**Comment by akurtakov** [comment]
Opened (helpdesk issue)[https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1543]

**Comment by akurtakov** [comment]
Done by webmaster.
