### ISSUE TITLE
java.lang.SecurityException: class "org.eclipse.core.runtime.Plugin"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by estepper** [eclipse-equinox/equinox#39]
I updated my target platform to include the newest Eclipse I-build. Now my tests are starting to fail with the exception in the title.

It probably occurs because org.eclipse.core.runtime is a split package and the following two contributors have different certificates in the latest I-build:

org.eclipse.equinox.common
3.16.100.v20220315-2327
Built: 2022-06-14 at 23:03
Reported: 2022-06-17 at 05:20
![image](https://user-images.githubusercontent.com/101910/174318692-85ff1c45-fc10-4dff-9ac0-25511a5c97d9.png)

org.eclipse.core.runtime
3.25.100.v20220613-1008
Built: 2022-06-14 at 23:03
Reported: 2022-06-17 at 05:20
![image](https://user-images.githubusercontent.com/101910/174319348-d8003583-c5cd-4837-9f1f-a35e8bc315c0.png)

**Comment by merks** [comment]
Fixed in latest IBuild

org.eclipse.equinox.common
3.16.200.v20220617-1839
Built: 2022-06-18 at 08:41
Reported: 2022-06-19 at 05:41 
![image](https://user-images.githubusercontent.com/208716/174470148-04fa86f5-be09-437b-9a7e-b1facff47228.png)

**Comment by estepper** [comment]
Thanks!
