### ISSUE TITLE
Comparator error in org.eclipse.osgi module-info.class

### ISSUE THREAD

**Issue by akurtakov** [eclipse-equinox/equinox#42]
Visible in https://download.eclipse.org/eclipse/downloads/drops4/I20220618-1000/buildlogs/comparatorlogs/artifactcomparisons.zip .
- open module org.eclipse.osgi { // 3.18.100.202206180757
+ open module org.eclipse.osgi { // 3.18.100.202206181419

This fully qualified version shouldn't be there to not cause comparator error.

**Comment by akurtakov** [comment]
@laeubi Could you please look into the issue as there will be comparator issue on every build due to that.

**Comment by laeubi** [comment]
@akurtakov I wonder what this comparator error should tell us actually? Could the comparator be made more smart to ignore such (irrelevant?) differences?

**Comment by akurtakov** [comment]
It compares bytecode to bytecode changes. What we seen should be generated by https://github.com/eclipse/tycho/blob/master/tycho-artifactcomparator/src/main/java/org/eclipse/tycho/zipcomparator/internal/ClassfileComparator.java

**Comment by laeubi** [comment]
Okay hopefully @rotty3000 can give a hint if BND could be advised to not include the qualifier. on the other hand I have had thought that the qualifier stays the same and everything is fine after the version bump??

**Comment by akurtakov** [comment]
Qualifiers stays the same thanks to the comparator. Local build always uses qualifier with timestamp and if comparator says it's same bytecode as the one in the repo the newly built one is ditched and the old (remote) artifact is used from that point.

**Comment by laeubi** [comment]
> Local build always uses qualifier with timestamp

Why don't we use Jgit timestamps here?

**Comment by rotty3000** [comment]
You can set the version with the bnd jpms instruction to whatever you like. I'll give an example first thing tomorrow.

**Comment by laeubi** [comment]
@rotty3000 thanks for your support!
@mickaelistria do you know why not jgit is used for stable build qualifier?

**Comment by mickaelistria** [comment]
> @mickaelistria do you know why not jgit is used for stable build qualifier?

Not really, but the question is more why would the jgit build be used in order to configure the generated module-info.class ? Is the build configured so that the buildQualifier from Tycho is propagated to module-info.class generation?

**Comment by laeubi** [comment]
Currently the buildqualifier is included yes. We might change this, neverless it seems strange to use a (timestamped) one to replace it with baseline afterwards when we can use a stable jgit one at the first place...?

**Comment by mickaelistria** [comment]
>  neverless it seems strange to use a (timestamped) one to replace it with baseline afterwards when we can use a stable jgit one at the first place...?

What does generate the version in module-info.class ? That's what needs to be tweaked to use JGit version.
Note that the baseline may be incorrect here as well. One would expect the version to be 3.18.100.v20220618-0417 . So first thing to fix is to generate correct module version that is same as the OSGi bundle; and then we can just skip baseline replacement for some modules to deploy the fixed version without comparing with baseline (as baseline is currently wrong and not to be used as a reference).

**Comment by laeubi** [comment]
This is done by BND. Maybe @rotty3000 knows if we can inject a special version here? But maybe even better as @akurtakov suggested  don't include the qualifier at all.

**Comment by akurtakov** [comment]
Having qualifier in a comment in the bytecode makes no sense to me.

**Comment by mickaelistria** [comment]
> Having qualifier in a comment in the bytecode makes no sense to me.

It's printed as a comment, but it's actually semantically in the module info. If you introspect the Module, this version is visible via Java APIs.

**Comment by rotty3000** [comment]
hey all, you can add the `version` attribute to this instruction https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.osgi/bnd.bnd#L1

Note that in that instruction the value can make use of bnd macros.

To see the documentation on all that is possible with that look here https://bnd.bndtools.org/chapters/330-jpms.html

**Comment by rotty3000** [comment]
However, I think just doing a compare is flawed practice since that isn't going to handle actual changes that happen, or rather it will force you to ignore a failure when a change does happen. Then entire point here is that module-info actually be a LIVE representation of the ACTUAL module rather than a constantly stale one that you have to manually repair every 6 months.
