### ISSUE TITLE
Path with Array Overhead

### ISSUE THREAD

**Issue by jukzi** [eclipse-equinox/equinox#433]
In a heapdump of an OOME i can see ~ 10.000.000 Arrays with a single Element in Path.segments 
each Array has an overhead of 24 Bytes => ~ 0.25 GB memory wasted
![image](https://github.com/eclipse-equinox/equinox/assets/51790620/663a0fe8-5426-451a-bccb-d4bcaaf36202)

**Comment by laeubi** [comment]
> In a heapdump of an OOME i can see ~ 10.000.000 Arrays with a single Element in Path.segments

for me interesting question would be why are there `10.000.000` path objects stored, maybe IPath should maintain a (weak) cache to deduplicate items.

Second, maybe segments should be stored as `Object` instead of `String[]`, this would allow for single-array items to be stored as the single item, then only where the segment is accessed we need a

```
if (stored instanceof String[] array) {
  //its an array
else {
 //its stored as single String object
}
```

**Comment by jukzi** [comment]
> for me interesting question would be why are there `10.000.000` path objects stored,

The workspace keeps the history of the entire workspace up to the last state that is referenced by an incremental builder see
https://github.com/eclipse-platform/eclipse.platform/issues/910

> maybe IPath should maintain a (weak) cache to deduplicate items.

That's not possible with the current API since IPath can be constructed with constructor `new Path(args)` instead of a static method. That will be solved by https://github.com/eclipse-platform/eclipse.platform/pull/1015

> Second, maybe segments should be stored as `Object` instead of `String[]`, this would allow for single-array items to be stored as the single item, then only where the segment is accessed we need

Exactly that is the plan after https://github.com/eclipse-equinox/equinox/pull/431. We can even store [Object[] parentSegments, String childSegment] for the most frequent parent.append(child)

**Comment by laeubi** [comment]
> That's not possible with the current API since IPath can be constructed with constructor new Path(args)

We already have `IPath.of(....)` like Java did with Integer / Long and alike of course that must be used, but this is our own responsibility so I would suggest to add caching / de-duplication there and then clearly state that using that method is more memory efficient.

**Comment by mickaelistria** [comment]
I agree with @laeubi here that the array overhead could be marginal in this case of 10M Path objects; it's very likely that the much bigger issue is duplication of Path.
I see only 2 occurrences of `new Path(` text in "org.eclipse.core.resources", so we may be able to just replace those construction with a smarter one that would prevent useless instantiations (either by using `IPath.of()` and adding a cache there directly (and deprecating the `new Path` constructor in a further step), or by implementing caching in org.eclipse.core.resources and using it in the 2 occurrences of Path creation.

**Comment by jukzi** [comment]
All the offending Paths in the cache are constructed with IPath#append

**Comment by jukzi** [comment]
> a project name

all of them are like that in the heapdump i have. ~17000 Elementtree  with 769 (#projects)  Paths in childIDsCache each.
maybe org.eclipse.core.internal.watson.ElementTree.immutable() should just clear that cache for historic trees.

**Comment by mickaelistria** [comment]
>  ~17000 Elementtree with 769 (#projects) Paths in childIDsCache each.

OK, so do I get it right that if some caching happens in Path.append(String) when `this` is IPath.ROOT, then we go from a dozen millions of instances to just 769 here?

> maybe org.eclipse.core.internal.watson.ElementTree.immutable() should just clear that cache for historic trees.

Maybe, but that seems much more risky to change some state of ElementTree than to just enable some cache in Path.append. The history is an important and difficult piece to maintain, I would rather going too deep into it if we have identified another simpler solution that has no risk of causing regressions.

**Comment by jukzi** [comment]
This solution is so freaking simple compared to all other changes i tried: https://github.com/eclipse-platform/eclipse.platform/pull/1019

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform/commit/4e0f4a4911cf90fbd6a31261c34f23ae82e5b445 greatly improves memory consumption for the case shown in the ticket description. Let's assume it's closed then.

**Comment by jukzi** [comment]
The discussion was very helpfull to find the actual root cause, thanks
