### ISSUE TITLE
BasicLocationTests#testCreateLocation04() fails silently

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-equinox/equinox#460]
The test case `org.eclipse.osgi.tests.services.datalocation.BasicLocationTests#testCreateLocation04()` fails silently. The test runs into a `fail` statement, which is caught and ignored by a surrounding try-catch:

https://github.com/eclipse-equinox/equinox/blob/60a2e63e9c40fc480c90b3800d80b7c03b0602b9/bundles/org.eclipse.osgi.tests/src/org/eclipse/osgi/tests/services/datalocation/BasicLocationTests.java#L149-L155

I tried to replace this block with an `assertThrows` in #455, which fails because nothing is actually thrown.

I have not yet investigated whether the test or the tested functionality is faulty.

**Comment by tjwatson** [comment]
Apologize for the slow response, I must have missed this issue being open over the Holidays.  The test is indeed bogus and if properly written it would have caught a regression introduced by https://github.com/eclipse-equinox/equinox.framework/pull/39
