### ISSUE TITLE
Eclipse build process throws some warnings in Mac

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-equinox/equinox#472]
The Eclipse build.sh file encounters warnings during the build process on a Macbook Pro M1 running Sonoma (OS version 14.2.1). The warnings are related to three deprecated functions in the C programming language for macOS: `CFURLGetFSRef`, `FSResolveAliasFile`, and `CFURLCreateFromFSRef`.

Device Information:

- Device: Macbook Pro M1
- OS: Sonoma (14.2.1)

Steps to Reproduce:

- Attempt to build the Eclipse on a Macbook Pro M1 using the provided build.sh(features/org.eclipse.equinox.executable.feature/library/cocoa/build.sh) file.
- Encounter warnings related to the deprecated functions (`CFURLGetFSRef`, `FSResolveAliasFile`, `CFURLCreateFromFSRef`).

Expected Behavior:

- The build process should complete successfully without warnings related to deprecated functions.

Attachments:

- Attach relevant screenshots showing the warnings encountered during the build process.
<img width="1727" alt="Screenshot 2024-01-10 at 8 52 49 AM" src="https://github.com/eclipse-equinox/equinox/assets/117082823/48b62e0a-42ab-4ce1-a207-f922bdc3fe24">

**Comment by laeubi** [comment]
@subyssurendran666 do you like to propose a PR to fix those warnings?

**Comment by subyssurendran666** [comment]
> do you like to propose a PR to fix those warnings?

@laeubi yes I'm working on it.
