### ISSUE TITLE
Switch to macOS sdk version 11

### ISSUE THREAD

**Issue by Phillipus** [eclipse-equinox/equinox#473]
See discussion here https://github.com/eclipse-platform/eclipse.platform.swt/pull/771 and comments from @sravanlakkimsetti concerning switching.

Is it as simple as re-instating the following commit?

https://github.com/eclipse-equinox/equinox/commit/0dad4635cce80cdc9a16764b8470b56ee421d058

**Comment by Phillipus** [comment]
@sravanlakkimsetti Thank-you. I will test the next I-Build.

**Comment by sravanlakkimsetti** [comment]
The launcher has been rebuilt and committed to equinox.binaries via https://github.com/eclipse-equinox/equinox.binaries/commit/87fa48322c83e564d062a145a0f987f130d8b65a

**Comment by Phillipus** [comment]
> The launcher has been rebuilt and committed to equinox.binaries via [eclipse-equinox/equinox.binaries@87fa483](https://github.com/eclipse-equinox/equinox.binaries/commit/87fa48322c83e564d062a145a0f987f130d8b65a)

I downloaded the `eclipse` and `eclipse_11803.so` binaries and ran the command `otool -l <filename>` on them. The SDK reported is 13.0:

```
Load command 8
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 11.0
      sdk 13.0
```

Does that mean they will only work on a minimum of macOS 13 (Ventura)?

**Comment by Phillipus** [comment]
Testing with latest launcher binary and with latest java 17 with child Eclipse and RCP app I see a problem in Trees with clipping of text:

<img width="451" alt="Screenshot 2024-01-11 at 15 40 20" src="https://github.com/eclipse-equinox/equinox/assets/600504/2610e6f1-f55f-4f72-801b-30325d93a959">

I seem to remember a clipping problem like this before and a workaround was applied.

**Comment by Phillipus** [comment]
This was originally patched here:

https://github.com/eclipse-platform/eclipse.platform.swt/commit/0e67434ae15877bd0853a47e92ba969bfe56f507

Changing the line by removing `&& !OS.IS_X86_64` fixes it:

```java
if (OS.isBigSurOrLater()) width += Tree.TEXT_GAP;
```

But I'm not sure how this will affect users not on latest Java.

**Comment by Phillipus** [comment]
What concerns me is places in the code that call `OS.IS_X86_64` such as the line above and elsewhere. There are places in SWT code that assume that a difference is caused by OS architecture but in fact may be caused by SDK version. For example in `OS` class:

```java
public static final int NSTextAlignmentCenter = IS_X86_64 ? 2 : 1;
public static final int NSTextAlignmentRight = IS_X86_64 ? 1 : 2;
```

**Comment by Phillipus** [comment]
I opened PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/969 for the text clipping bug.

**Comment by Phillipus** [comment]
@sravanlakkimsetti I'm confused. It seems that the launcher for Eclipse 4.30 macOS x86_64 is already built using the later SDK.

Here's the result of `vtool -show Eclipse.app/Contents/MacOS/eclipse` for Eclipse 4.30:

```
Load command 9
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.10
      sdk 13.0
Load command 10
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
```

And for Eclipse 4.29:

```
Load command 9
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.10
      sdk 10.14
Load command 10
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
```

**Comment by sravanlakkimsetti** [comment]
I moved min version to 11 now. Lets give it a try

**Comment by Phillipus** [comment]
> I moved min version to 11 now. Lets give it a try

Yes, I see that. But it seems that the x86_64 launcher has been built with SDK 13 already for some time (at least since Eclipse 4.30). So the original issue is not necessary.
