### ISSUE TITLE
org.eclipse.equinox.http.service.api missing?

### ISSUE THREAD

**Issue by andrew-tram** [eclipse-equinox/equinox#487]
Does `org.eclipse.equinox.http.service.api` need to be included in a feature to be packaged? I dont see it listed out in build outputs - https://download.eclipse.org/equinox/drops/I20240122-1800/index.php

**Comment by HannesWell** [comment]
Looks like it is not assigned to this special p2-repository.

But it is contained in the latest I-builds repository:
https://download.eclipse.org/eclipse/updates/4.31-I-builds/I20240122-1800

**Comment by andrew-tram** [comment]
Ahh gotcha, thanks for the heads up. Will it / should it be contained in this p2-repo though?

**Comment by laeubi** [comment]
> Ahh gotcha, thanks for the heads up. Will it / should it be contained in this p2-repo though?

If it is required it will be included in the usual release repositories, I'll close this issue now unless we got some more context information where it is specifically missing.
