### ISSUE TITLE
Getting java.lang.NoSuchMethodError:org.eclipse.equinox.http.jetty.interna.HttpServerManager.sessionDestroyed()Ljava/lang/String; 

### ISSUE THREAD

**Issue by abirla-tibco** [eclipse-equinox/equinox#505]
I am using org.eclipse.equinox.http.jetty.3.7.600 jar and i am getting an error as java.lang.NoSuchMethodError:org.eclipse.equinox.http.jetty.interna.HttpServerManager.sessionDestroyed()Ljava/lang/String; 

It was giving this error because, HttpServerManager does not have a method named sessionDestroyed() which takes string as a parameter , In this class we have one inner class and that inner class is having this method , which takes javax.servlet.http.HttpSessionEvent.java class object as a parameter and it is a public method. 

So there is parameter mismatch. so in order to fix the issue i have overriden the Activator.java and HttpServerManager.java class and did some modification.

In Activator , the place where they were creating the object of org.eclipse.equinox.http.jetty.interna.HttpServerManager , i have created the object of my own HttpServerManager and gave a call to MyHttpServermanager's update() method .

And in HttpServerManager there is one inner class called InternalHttpServiceServlet , and in this class we have two method of type final and these two methods are getting initalized using reflation and wrong parameters are getting passed while inializing [ passing string as a parameter whereas the sessionDestroyed() was expacting the object of HttpSessionEvent as the parameter ]   in the constructor of inner class , so here i have removed the final keyword so that i don't need to initlaize them in the constuctor, now at my end everything is working fine.

so while intializing sessionDestroyed() method and sessionIdChanged() method , I am attching the screenshot of the code which is there in the jar and the code my overridden class where i have made the necessary changes to make it work.

![HttpServerManager_Overridden](https://github.com/eclipse-equinox/equinox/assets/159138756/8f9d60b6-ac9f-48b0-8cff-7ae9e4f1e8f8)

![HttpServerManager_Orginal](https://github.com/eclipse-equinox/equinox/assets/159138756/19401a8f-cba2-4129-a7be-9681db28294a)
![sessionDestroyed_method_of_orginal_jar](https://github.com/eclipse-equinox/equinox/assets/159138756/4e939c67-19b8-473c-b545-f925aee76a54)

**Comment by laeubi** [comment]
@anjali-birla I think the best would be to create a PR if you like to suggest some changes (you can simply edit the file in the github web UI)

**Comment by anjali-birla** [comment]
Can you please tell me the process to create a PR.

**Comment by anjali-birla** [comment]
Sure , I will create a PR.
