### ISSUE TITLE
[macOS] CLASS: class 'KeyWindow' 0x113dea680 small method list 0x113de4c68 is not in immutable memory

### ISSUE THREAD

**Issue by rgrunber** [eclipse-equinox/equinox#508]
In https://github.com/redhat-developer/vscode-java/issues/3484 multiple users have noted that with `org.eclipse.equinox.launcher.cocoa.macosx.x86_64`, sometime between `1.2.800.v20231003-1442` & `1.2.900.v20240129-1338`, the Eclipse runtime containing that bundle (likely on MacOS 10.15.6 and below, so an older version) stopped working.

The following error stood out :

`objc[53522]: CLASS: class 'KeyWindow' 0x113dea680 small method list 0x113de4c68 is not in immutable memory`

This `KeyWindow` : https://github.com/eclipse-equinox/equinox/blob/6aca5d37f5d64358a205e9ced442a26cd47577b2/features/org.eclipse.equinox.executable.feature/library/cocoa/eclipseCocoa.c#L87 ?

Is there anything that may have caused this ?

**Comment by iloveeclipse** [comment]
> Is there anything that may have caused this ?

May be I'm wrong, but I believe the binaries were compiled against higher Apple platform and may be this causes problems with older MacOs.

**Comment by rgrunber** [comment]
Thanks for the hint. Yeah it could definitely be https://github.com/eclipse-equinox/equinox/pull/474 . @iloveeclipse  Is there any harm to removing the fragment as a workaround for just those affected users/platforms ? From my testing, the (headless) language server seems to be working without it so I wonder if the embedded binary does anything of value after Eclipse has already started.

**Comment by iloveeclipse** [comment]
No idea.

**Comment by rgrunber** [comment]
Closing, as the issue is known and because I believe the bundles need not be included in the particular workflow I was interested in.
