### ISSUE TITLE
MacOS launcher artifacts test failing in the github workflows

### ISSUE THREAD

**Issue by subyssurendran666** [eclipse-equinox/equinox#534]
<img width="590" alt="Screenshot 2024-02-16 at 7 19 51 PM" src="https://github.com/eclipse-equinox/equinox/assets/117082823/a7783274-565a-4283-a5c6-7135ee3a2166">

**Comment by subyssurendran666** [comment]
https://github.com/eclipse-equinox/equinox/pull/491

**Comment by subyssurendran666** [comment]
https://github.com/eclipse-equinox/equinox/pull/535

**Comment by HannesWell** [comment]
> #535

With that I think this can be considered resolved. Thanks for your contribution.
