### ISSUE TITLE
Multiple versions of Jetty bundles cause Missing Constraint problems

### ISSUE THREAD

**Issue by andrew-tram** [eclipse-equinox/equinox#558]
I was suggested to bring  this - https://github.com/jetty/jetty.project/issues/11541 - over to here.

Jetty Version

Jetty 10.0.20 and 12.0.6

Jetty Environment

Probably not applicable.

Java Version

Java 21

Question

Is it expected that having multiple versions of Jetty plugins will cause Missing Constraint problems? I need to have both versions to satisfy dependencies. EGit seems to require Jetty 10.x and in-house, Eclipse 4.31, and WTP 3.33 plugins need Jetty 12.x

With everything selected:
![image](https://github.com/eclipse-equinox/equinox/assets/106191140/9b0c8d6b-4400-4a8b-b39f-0a5318f284d8)

With just 12.x selected:
![image](https://github.com/eclipse-equinox/equinox/assets/106191140/6a3fc270-ef3b-4858-aa6c-20050124654a)

With just 10.x selected:
![image](https://github.com/eclipse-equinox/equinox/assets/106191140/21392c70-f5f4-4bd8-ac7a-3624b6648c0c)

**Comment by laeubi** [comment]
What Eclipse version are you using? Please make sure to use the latest2024-03 release.
Beside that have you tried using "Include Required Plugins" option?

**Comment by andrew-tram** [comment]
Yes, the RCP application is 4.31 (2024-03). It builds/packages just fine and includes the required bundles needed to run. But when using the application to launching a self targeting debug instance, I get the following above, which lead me to believe only one major version or Jetty can be included in a given product. On the Jetty side, they believe multiple versions can be contained in an application and to check with the osgi/ equinox folks.

**Comment by laeubi** [comment]
If you just run the project do you get any errors? Sadly sometimes the validation dialog is not smart enough and gives false positive warnings, in that case this would be something to report to PDE as a bug.

In general it works to have as many versions as you want.

**Comment by merks** [comment]
I see the same thing launching BIRT:

![image](https://github.com/eclipse-equinox/equinox/assets/208716/743311d6-a209-4f6a-8221-213c0fd603c6)

But it runs fine.

The validation is done by PDE, so yes, it appears to be a PDE bug.

We can't move the issue to a different organization, so please open an issue for PDE.
