### ISSUE TITLE
Eclipse fails to launch after update with JRE 22.0.1: java.lang.NoSuchMethodError: getMainType

### ISSUE THREAD

**Issue by kevinmilner** [eclipse-equinox/equinox#610]
First of all, apologies if this is the wrong place to report this issue; I'm happy to resubmit elsewhere. As it's a launching issue, I'm thinking it might be due to equinox, but I really don't understand the eclipse project structure well at all.

I'm running eclipse 2024-03 (4.31.0) on Ubuntu 24.04. I just updated via Oomph, which downloaded a new JRE: 22.0.1. Upon restarting (and all subsequent attempts), I can no longer launch eclipse. I get this error message in a GUI text window:

```
JVM terminated. Exit code=1
/home/kevin/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_22.0.1.v20240426-1149/jre/bin/java
-Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclientjava
-Dosgi.requiredJavaVersion=17
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Declipse.e4.inject.javax.warning=false
-Dsun.java.command=Eclipse
-Xms256m
-Xmx2048m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-Djava.security.manager=allow
-Declipse.p2.max.threads=10
-Doomph.update.url=https://download.eclipse.org/oomph/updates/milestone/latest
-Doomph.redirection.index.redirection=index:/->https://raw.githubusercontent.com/eclipse-oomph/oomph/master/setups/
--add-opens=java.base/java.lang=ALL-UNNAMED
-jar /opt/eclipse/java-2024-03/eclipse//plugins/org.eclipse.equinox.launcher_1.6.700.v20240213-1244.jar
-os linux
-ws gtk
-arch x86_64
-showsplash /home/kevin/.p2/pool/plugins/org.eclipse.epp.package.common_4.31.0.20240307-1200/splash.bmp
-launcher /opt/eclipse/java-2024-03/eclipse/eclipse
-name Eclipse
--launcher.library /home/kevin/.p2/pool/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.900.v20240129-1338/eclipse_11900.so
-startup /opt/eclipse/java-2024-03/eclipse//plugins/org.eclipse.equinox.launcher_1.6.700.v20240213-1244.jar
--launcher.appendVmargs
-exitdata 2800d
-product org.eclipse.epp.package.java.product
-vm /home/kevin/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_22.0.1.v20240426-1149/jre/bin/java
-vmargs
-Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclientjava
-Dosgi.requiredJavaVersion=17
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Declipse.e4.inject.javax.warning=false
-Dsun.java.command=Eclipse
-Xms256m
-Xmx2048m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-Djava.security.manager=allow
-Declipse.p2.max.threads=10
-Doomph.update.url=https://download.eclipse.org/oomph/updates/milestone/latest
-Doomph.redirection.index.redirection=index:/->https://raw.githubusercontent.com/eclipse-oomph/oomph/master/setups/
--add-opens=java.base/java.lang=ALL-UNNAMED
-jar /opt/eclipse/java-2024-03/eclipse//plugins/org.eclipse.equinox.launcher_1.6.700.v20240213-1244.jar 
```

And I see this if I launch it on a command line:

```
Exception in thread "main" java.lang.NoSuchMethodError: getMainType
```

I can manually launch eclipse by reverting to JRE 22.0.0 (rather than 22.0.1). There are no available updates when I do so.

**Comment by iloveeclipse** [comment]
@merks : something for you?

**Comment by merks** [comment]
A full stack trace would help. 

It might well be the case that Java 22 breaks something that equinox needs to address.  Java introducing breaking changes would not be a new thing.

**Comment by kevinmilner** [comment]
@merks do you know how to enable full stack traces when launching eclipse? All I get when launching is the exception message as pasted without the trace.

**Comment by merks** [comment]
It works for me on Windows:

![image](https://github.com/eclipse-equinox/equinox/assets/208716/ba16e1f4-d956-4138-b6a2-a018bfc513e8)

**Comment by merks** [comment]
Maybe running with -consoleLog will produce more output that includes a full stack trace.  I can't find anything in Equinox or the Platform with a method name "getMainType", so that kind of odd.  

If you create a new installation, does that also fail to start?

**Comment by kevinmilner** [comment]
Adding -consoleLog didn't give any extra information, but doing a clean install did seem to fix things. No clue what happened, but I'll close as I have it working now. Thanks for doing some digging on your end!

I did find that `getMainType` is in the [JDT project](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.core.manipulation/core%20extension/org/eclipse/jdt/internal/corext/refactoring/util/JavaElementUtil.java). Maybe that package was corrupted during the update?
