### ISSUE TITLE
Unable to satisfy dependency to macosx aarch64 launcher

### ISSUE THREAD

**Issue by nullterminated** [eclipse-equinox/equinox#726]
Hii there. It took me a while to hunt down where to report this. I hope this is the right place.

I have an eclipse product build that was working with 2024-09 before the release of 2024-12. Now the product build fails due to,

[WARNING] Mirror tool: Problems resolving provisioning plan.:
   Unable to satisfy dependency from wolips.product.executable.cocoa.macosx.aarch64 5.0.0.202412161006 to org.eclipse.equinox.p2.iu; org.eclipse.equinox.launcher.cocoa.macosx 0.0.0, filter=(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa)).

Only the macosx aarch64 product build fails. If I comment out that one platform, everything else succeeds. But since this is a product mainly targeted to developers on mac os, that is the most important one :)

It is  an open source project, so you can check out the source yourself at

https://github.com/wocommunity/wolips

Switch to the wolips5 branch
Uncomment the wolips.product module in wolips/wolips/pom.xml
then 'mvn clean package'

You should see the same error. Is there something special that needs to be done specifically for macosx-aarch64 since 2024-12?

**Comment by laeubi** [comment]
Have you tried latest Tycho 4.0.10 (or even 
try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build)?

**Comment by nullterminated** [comment]
There's a new one? Aaaannd, it works. You guys are incredible. Thanks so much!

**Comment by laeubi** [comment]
No problem, things are changing fast and sometimes a new Eclipse-Release needs a new Tycho release to catchup with some changes in the underlying techniques (e.g. P2)

**Comment by nullterminated** [comment]
I will keep that in mind in future release cycles. Thanks again. I love the new target platforms too :)
