### ISSUE TITLE
10 failing osgi.tests since I20220715-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/equinox#81]
https://download.eclipse.org/eclipse/downloads/drops4/I20220715-1800/testresults/html/org.eclipse.osgi.tests_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

Probably side effect of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/389 changes.
All test hit an assert with this message: `Failure | 0.0.1.org.junit.platform.commons`.

**Comment by HannesWell** [comment]
This will likely fixed as soon as the pending https://github.com/eclipse-platform/eclipse.platform/pull/46 is available from I-builds.
I think it depends on the other two pending PRs in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/389.

**Comment by mickaelistria** [comment]
This seems all good now: https://download.eclipse.org/eclipse/downloads/drops4/I20220718-1800/testresults/html/org.eclipse.osgi.tests_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html
