### ISSUE TITLE
I-build failure with missing `com.ibm.oti.shared`

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-equinox/equinox#83]
We are getting this error 
```
 [ERROR] Cannot resolve project dependencies:
 [ERROR]   Software being installed: org.eclipse.equinox.weaving.caching 1.2.200.qualifier
 [ERROR]   Missing requirement: org.eclipse.equinox.weaving.caching 1.2.200.qualifier requires 'java.package; com.ibm.oti.shared 0.0.0' but it could not be found
 [ERROR] 
 [ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
 [ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.equinox:org.eclipse.equinox.weaving.caching:1.2.200-SNAPSHOT @ /home/jenkins/agent/workspace/I-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/equinox/bundles/org.eclipse.equinox.weaving.caching/.polyglot.META-INF: See log for details -> [Help 1]
 [ERROR] 
 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
 [ERROR] 
 [ERROR] For more information about the errors and possible solutions, please read the following articles:
 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by merks** [comment]
That's an option requirement though and has generally never been satisfied:

![image](https://user-images.githubusercontent.com/208716/180142694-89546d7a-a9b7-4a89-95a6-e26f35208163.png)

**Comment by sravanlakkimsetti** [comment]
the build is failing. Probably a regression from https://github.com/eclipse-equinox/equinox/commit/1b8d960f72ccc273431f9cc8df774c56c4e829c9#diff-7fd57176fc2abda648039f644c6bf58df70b006bd5231ff47e7b8de0812d5969

@HannesWell Can you please take a look?

**Comment by akurtakov** [comment]
Looks like https://github.com/eclipse-equinox/equinox/blob/a1a9eaf5879c77a3aa029ac318a826cceadb59ff/bundles/org.eclipse.equinox.weaving.caching/build.properties#L20 is not used. @HannesWell @laeubi can you look into this? Hopefully a fast fix to unbreak build if tycho needs to be patched.

**Comment by laeubi** [comment]
As the local build seems to succeed I suspect the I-Build is not using latest tycho-build extension (2.7.4) where this was fixed.

**Comment by akurtakov** [comment]
You're right, it uses 2.7.2. I'll update now.

**Comment by HannesWell** [comment]
Yes, as Christoph said Tycho 2.7.4 is definitivly requird. Thank you for fixing.
It supprises me that the build did not fail earlier respectivly didn't had many test failures and much less Test executions. But I have to admit I didn't check that yet.

**Comment by akurtakov** [comment]
So when equinox repo is build, extensions.xml file in it is used (2.7.4) but when whole aggregator is used extensions.xml file from parent dir is used (2.7.2). For me this explains a lot. Too bad we can't have same extensions.xml file used even for submodules.

**Comment by laeubi** [comment]
Maven uses the first it find starting from the build directory down to the root. I don't think using different ones in the same reactor would be possible because then these could conflict with each other. Of course one could thing of instead of one bug pom that mentions all module, building each of it alone, but this would require that one impose a total ordering of projects and that there are no cross-references.
